DROP DATABASE IF EXISTS BBDD_TENISTAS;
  
  CREATE DATABASE IF NOT EXISTS  BBDD_TENISTAS;
  
  USE BBDD_TENISTAS;


DROP TABLE IF EXISTS TENISTAS;
  CREATE TABLE IF NOT EXISTS TENISTAS
  (
  DNI      CHAR(9) NOT NULL,
  NUM_AFILIADO  SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE_COMPLETO  VARCHAR(10) NOT NULL,
  FECHA_NACIMIENTO  DATE NOT NULL,
  PESO         INT NULL,
  ENTRENADOR   CHAR(9) NOT NULL,
  INDEX FK_TENISTA_ENTRENADOR(ENTRENADOR),
  PRIMARY KEY (NUM_AFILIADO),
  UNIQUE INDEX AK_DNI (DNI)
  )ENGINE INNODB;

  
  DROP TABLE IF EXISTS TORNEOS;
  CREATE TABLE IF NOT EXISTS TORNEOS
  (
  
  NOMBRE      VARCHAR(10)    NOT NULL,
  FECHA_INICIO  DATE NOT NULL,
   número_jornadas INT NOT NULL,
  PAIS_ELABORADO  ENUM('INGLATERRA, FRANCIA,ESPAÑA, EEUU, SUIZA, ARGENTINA') NOT NULL,
  ID_TORNEO SMALLINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID_TORNEO)
  )ENGINE INNODB;
  
  DROP TABLE IF EXISTS PARTIDOS;
  CREATE TABLE IF NOT EXISTS PARTIDOS
  (
  NUMERO_PARTIDO     INT NOT NULL,
  FECHA_INICIO  DATE NOT NULL,
  HORA_INICIO  INT NOT NULL,
  DURACION  INT NOT NULL,
  
  PRIMARY KEY (NUMERO_PARTIDO)
  )ENGINE INNODB;
  
  DROP TABLE IF EXISTS EQUIPO_NACIONALES;
  CREATE TABLE IF NOT EXISTS EQUIPO_NACIONALES
  (
  ID_EQUIPO SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE_PAIS       VARCHAR(10)   NOT NULL,
  NOMBRE_SELECIONADOR    VARCHAR(10) NULL,
  CAPITAN   SMALLINT UNSIGNED NOT NULL,
  INDEX FK_TENISTA_CAPITAN(CAPITAN),
  PRIMARY KEY (ID_EQUIPO)
  
  )ENGINE INNODB;
  
  DROP TABLE IF EXISTS TENISTAS_TORNEOS;
  CREATE TABLE IF NOT EXISTS TENISTAS_TORNEOS
  (
  TENISTA SMALLINT UNSIGNED NOT NULL,
  FOREIGN KEY (TENISTA) REFERENCES TENISTAS(NUM_AFILIADO)
            ON DELETE CASCADE 
            ON UPDATE CASCADE,
  INDEX FK_TENISTA_PARTICIPA(TENISTA),
  TORNEO  SMALLINT NOT NULL,
  FOREIGN KEY (TORNEO) REFERENCES TORNEOS(TORNEO)
            ON DELETE CASCADE 
            ON UPDATE CASCADE,
  INDEX TORNEOS(TORNEO),
  PRIMARY KEY (TENISTAS,TORNEO)
  )ENGINE INNODB;

 ALTER TABLE TENISTAS
     ADD FOREIGN KEY (TENISTAS) REFERENCES TENISTAS(NUM_AFILIADO)
            ON DELETE SET NULL 
             ON UPDATE CASCADE