/** VAMOS A PROBAR LOS DISPARADORES  1,2 Y 3 
QUE AUDITAN LA TABLA EMPLEADOS_PROYECTOS
*******************/
SELECT * FROM AUDITA_EMPLEADOS_PROYECTOS;
SELECT * FROM EMPLEADOS_PROYECTOS WHERE EMPLEADO=9;
UPDATE `empresa`.`EMPLEADOS_PROYECTOS` SET `PRECIO_HORA` = '150' 
WHERE (`EMPLEADO` = '3') and (`PROYECTO` = '1');

/** SE LANZA  UNA VEZ EL DISPARADOR AUDITA_EMPLEADOS_PROYECTOS3***/

UPDATE `empresa`.`EMPLEADOS_PROYECTOS` 
SET `NUM_HORAS` = '123', `PRECIO_HORA` = '120' 
WHERE (`EMPLEADO` = '9') and (`PROYECTO` = '8');

/** SE LANZA UNA VEZ  EL DISPARADOR AUDITA_EMPLEADOS_PROYECTOS3***/

UPDATE EMPLEADOS_PROYECTOS
   SET PRECIO_HORA= PRECIO_HORA*1.2
   WHERE EMPLEADO IN (1,2,4,8,9,10);
   /** SE LANZA EL DISPARADOR AUDITA_EMPLEADOS_PROYECTOS3 ,  
    UNA VEZ POR CADA TUPLA MODIFICADA **/
   
  SELECT * FROM AUDITA_EMPLEADOS_PROYECTOS; 
   
   INSERT INTO EMPLEADOS_PROYECTOS
   (EMPLEADO, PROYECTO, FECHA_INICIO)
   VALUES
   (1,1,CURRENT_DATE()),
   (1,3, CURRENT_DATE()),
   (1,6,'2021-05-01');
   
/** SE LANZA EL DISPARADOR AUDITA_EMPLEADOS_PROYECTOS1 , UNA VEZ POR CADA TUPLA INSERTADA**/

SELECT * FROM AUDITA_EMPLEADOS_PROYECTOS;


delete from empleados_proyectos
where empleado=1 and proyecto=1;

/** LANZA UNA VEZ EL DISPARADOR AUDITA_EMPLEADOS_PROYECTOS2 **/

SELECT * FROM AUDITA_EMPLEADOS_PROYECTOS; 