/** AHORA TENEMOS QUE PROBAR LA FUNCIÓN, LA TENEMOS QUE LANZAR*/
/* EJECUTA CADA ORDEN POR SEPARADO , ORDEN LÍNEA 4, LUEGO SOLO ORDEN EN LÍNEA 8,.LUEGO ORDEN L.INEA 12...*/

SELECT NUM_EMPLEADOS_DEP(1); 
                    /* DEPARTAMENTO DE CLAVE 1 TIENE 3 EMPLEADOS*/

/* HAY QUE PROBAR SI ARGUMENTO ES UN ENTERO CON VALOR DE DEPARTAMENTO QUE NO EXISTE*/
SELECT NUM_EMPLEADOS_DEP(123);
                   /*DEPARTAMENTO QUE NO EXISTE 123 TIENE  0 EMPLEADOS, NO ROMPE */


SELECT NUMERO, NOMBRE, NUM_EMPLEADOS_DEP(NUMERO) AS CANTIDAD_EMPLEADOS
    FROM DEPARTAMENTOS;
                    /** EN ESTA SELECT, POR CADA TUPLA SELECCIONADA, TODAS LAS DE TABLA DEPARTAMENTOS
                         PINTAMOS COLUMNA NUMERO, NOMBRE Y
                        LANZAMOS UNA VEZ LA FUNCIÓN 
                     **/

SELECT   D.NOMBRE AS DEPARTAMENTO,
         ( 
            SELECT NOMBRE
               FROM EMPLEADOS
               WHERE ID_EMPLEADO=D.DIRECTOR
         )AS SU_DIRECTOR
    FROM DEPARTAMENTOS AS D
    WHERE NUM_EMPLEADOS_DEP(D.NUMERO) >3;

/** AQUÍ EN ESTA SELECT, ESTAMOS USANDO LA FUNCIÓN DENTRO DE CLAÚSULA WHERE
     POR CADA TUPLA DE LA TABLA DEPARTAMENTOS, LANZAMOS UNA VEZ LA FUNCIÓN,
     EL  ARGUMENTO QUE PASAMOS  ES  LA COLUMNA NUMERO DE CADA TUPLA DE TABLA D
     Y COMPARAMOS VALOR QUE RETORNA CON 3, SI ES > 3 LA TUPLA QUEDA SELECCIONADA
**/