/** AHORA QUEREMOS DISPONER DE UNA FUNCIÓN
    QUE DEVUELVA LA CANTIDAD DE EMPLEADOS ASIGNADOS A UN DEPARTAMENTO PERO ESTA VEZ 
    !!!  RECIBE EL  NOMBRE DEL DEPARTAMENTO, NO SU CLAVE */


/* NO DISPONEMOS DE SOBRECARGA DE MÉTODOS , NO PODEMOS TENER IMPLEMENTADAS
   DOS FUNCIONES EN LA BASE DE DATOS CON EL MISMO NOMBRE, POR TANTO, ESTA FUNCIÓN REALIZA LA MISMA TAREA
   PERO EL ARGUMENTO QUE RECIBE ES UNA CADENA CON EL NOMBRE DEL DEPARTAMENTO ( RECORDAD QUE EN NUESTRA BASE DE DATOS
   NOMBRE DE DEPARTAMENTO ES AK, DATO ÚNICO, TIENE SENTIDO BUSCAR POR NOMBRE DE DEPARTAMENTO )
   
**/
/* LA FUNCIÓN NO PODRÁ LLAMARSE NUM_EMPLEADOS_DEP PORQUE YA TENEMOS UNA CON ESE NOMBRE*/

/* PRIMERO DISEÑAMOS LA CABECERA, RECIBE UN DATO, BUSCAMOS TIPO DE DATO DEFINIDO EN LA BASE DE DATOS PARA NOMBRE
   DE DEPARTAMENTO, RETORNARÁ UN  ENTERO CON LA CANTIDAD DE EMPLEADOS
*/ 

DELIMITER $$
USE EMPRESA$$

DROP FUNCTION IF EXISTS NUM_EMPLEADOS_NOMB_DEP$$

CREATE FUNCTION NUM_EMPLEADOS_NOMB_DEP( NOMBRE_DEP VARCHAR(25))
RETURNS INT
READS SQL DATA
BEGIN
   DECLARE CANTIDAD_EMPLEADOS INT;
   
   SELECT  COUNT(*) INTO CANTIDAD_EMPLEADOS
      FROM EMPLEADOS
      WHERE DEPARTAMENTO=(
                            SELECT NUMERO
                              FROM DEPARTAMENTOS
                              WHERE NOMBRE=NOMBRE_DEP
                         ); /* EN ESTA SUBCONSULTA  BUSCAMOS LA CLAVE DEL DEPARTAMENTO
                              CUYO NOMBRE ES = A EL DATO RECIBIDO EN LA LLAMADA Y QUE TENGO
                              ALMACENADO EN PARÁMETRO NOMBRE_DEP*/

   RETURN CANTIDAD_EMPLEADOS;

END$$

/** AHORA EJECUTAMOS ESTE SCRIPT DE CREACIÓN DE UN NUEVO OBJETO, OBJETO DE TIPO FUNCTION*/
/* DESPUÉS PARTE IDQUIERDA SOBRE LA BASE DE DATOS REFRESCA Y DESPLIEGA ROUTINES, 
    !YA TIENES LA FUNCIÓN IMPLEMENTADA!
     YA DISPONEMOS DE DOS OBJETOS MÁS EN NUESTRA BASE DE DATOS, DOS FUNCIONES**/
/**AHORA HAY QUE PROBARLA, TENEMOS QUE LANZARLA, DENTRO DEL CUERPO DE UNA RUTINA PODEMOS TENER ERRORES
   DE EJECUCIÓN, QUE SE DETECTAN PROBANDO, EJECUTANDO LA RUTINA**/
/** ABRE SCRIPT 4_PROBAR FUNCION NUM_EMPLEADOS_NOMB_DEP**/ 

