/** AHORA TENEMOS QUE PROBAR LA FUNCIÓN, LA TENEMOS QUE LANZAR*/
/* EJECUTA CADA ORDEN POR SEPARADO, PRIMERO ORDEN EN LÍNEA 4, LUEGO ORDEN EN LÍNEA 8,..*/

SELECT NUM_EMPLEADOS_NOMB_DEP('VENTAS'); 
                    /* CANTIDAD DE EMPLEADOS DE VENTAS  4 EMPLEADOS*/

/* HAY QUE PROBAR SI ARGUMENTO ES UN  VALOR DE DEPARTAMENTO QUE NO EXISTE*/
SELECT 00NUM_EMPLEADOS_NOMB_DEP('DEPARTAMENTO NO EXISTE');
                   /* 0 EMPLEADOS*/


SELECT NUMERO, NOMBRE, NUM_EMPLEADOS_NOMB_DEP(NOMBRE) AS CANTIDAD_EMPLEADOS
    FROM DEPARTAMENTOS;
           /** EN ESTA SELECT, POR CADA TUPLA SELECCIONADA, TODAS LAS DE LA TABLA DEPARTAMENTOS
                         PINTAMOS COLUMNA NUMERO, NOMBRE Y
                        LANZAMOS UNA VEZ LA FUNCIÓN , ESTA VEZ EL ARGUMENTO ES UNA CADENA CON EL NOMBRE
                     **/

SELECT   D.NOMBRE AS DEPARTAMENTO,
         ( 
            SELECT NOMBRE
               FROM EMPLEADOS
               WHERE ID_EMPLEADO=D.DIRECTOR
         )AS SU_DIRECTOR
    FROM DEPARTAMENTOS AS D
    WHERE NUM_EMPLEADOS_NOMB_DEP(D.NOMBRE) >3;

/** AQUÍ EN ESTA SELECT, ESTAMOS USANDO LA FUNCIÓN DENTRO DE CLAÚSULA WHERE
     POR CADA TUPLA DE LA TABLA DEPARTAMENTOS, LANZAMOS UNA VEZ LA FUNCIÓN,
     EL  ARGUMENTO QUE PASAMOS  ES  LA COLUMNA NOMBRE DE CADA TUPLA DE TABLA D
     Y COMPARAMOS VALOR QUE RETORNA CON 3, SI ES > 3 LA TUPLA QUEDA SELECCIONADA
**/

       