/** VAMOS A PROBAR NUESTRA FUNCIÓN
    SI_DIRECTOR
*/
/** EJECUTA CADA SENTENCIA POR SEPARADO*/

SELECT SI_DIRECTOR(9);

  /* QUÉ APARECE ? UN  CERO!! ESE ES VALOR DE FALSE  EL EMPLEADO DE ID 9 NO ES DIRECTOR**/

SELECT SI_DIRECTOR(4);
             /* QUÉ APARECE ? UN  UNO !! ESE ES VALOR DE TRUE  EL EMPLEADO DE ID 4 ES DIRECTOR**/
SELECT   ID_EMPLEADO, SALARIO
     FROM EMPLEADOS
     WHERE SI_DIRECTOR(ID_EMPLEADO);

   /** CLAVE Y NOMBRE DE LOS DIRECTORES**/

SELECT AVG(SALARIO)
    FROM EMPLEADOS
    WHERE SI_DIRECTOR(ID_EMPLEADO);  /** SALARIO MEDIO DE LOS DIRECTORES*/


/** PARA CADA EMPLEADO QUE SEA DIRECTOR SU NOMBRE, SALARIO Y CANTIDAD DE PROYECTOS EN LOS QUE TRBAJA*/


SELECT   E.NOMBRE,
         COUNT(EP.PROYECTO) AS CANTIDAD_PROYECTOS_TRABAJA
     FROM EMPLEADOS AS E LEFT JOIN EMPLEADOS_PROYECTOS AS EP
                               ON E.ID_EMPLEADO=EP.EMPLEADO
     WHERE SI_DIRECTOR(E.ID_EMPLEADO)
     GROUP BY E.ID_EMPLEADO;