DELIMITER $$
USE EMPRESA$$
DROP PROCEDURE IF EXISTS SUBIDA_SUELDO $$
CREATE PROCEDURE SUBIDA_SUELDO (IN PORCENTAJE FLOAT, IN TIPO INTEGER,IN NOMBRE_DEP VARCHAR(25), OUT OK BOOLEAN)
MODIFIES SQL DATA
BEGIN

DECLARE VAR_CLAVE_DEP  INTEGER UNSIGNED;
DECLARE MENSAJE VARCHAR(128);

DECLARE EXIT HANDLER FOR SQLEXCEPTION
 BEGIN
      SET OK=FALSE;
      SET MENSAJE=CONCAT('NO SE REALIZA LA OPERACIÓN ', TIPO , PORCENTAJE );
      INSERT INTO MENSAJES_DE_ERROR
       SELECT MENSAJE;
 
 END;

/**********************  PROCESO*************************/
CREATE TABLE IF NOT EXISTS  MENSAJES_DE_ERROR
(
   LINEA_TEXTO VARCHAR(128)
) ENGINE MyISAM;
SET OK=TRUE;
IF TIPO<1 OR TIPO>3
        THEN
             SET OK=FALSE;
             INSERT INTO MENSAJES_DE_ERROR            
                SELECT 'NO SE REALIZA LA OPERACIÓN , VALOR DE TIPO INCORRECTO ';
ELSE
	CASE TIPO
	WHEN 1 THEN  UPDATE EMPLEADOS
			SET SALARIO=SALARIO+ SALARIO*PORCENTAJE/100;
                           
	WHEN 2 THEN   UPDATE EMPLEADOS
			SET SALARIO=SALARIO+ SALARIO*PORCENTAJE/100
	        WHERE ID_EMPLEADO IN (SELECT DIRECTOR
			FROM DEPARTAMENTOS);
                                /*    
                                   UPDATE EMPLEADOS INNER JOIN DEPARTAMENTOS
                                                 ON E.ID_EMPLEADO=D.DIRECTOR
                                    SET SALARIO=SALARIO+ SALARIO*PORCENTAJE/100;             
                                */
                                                       
	WHEN 3 THEN  SELECT  NUMERO INTO VAR_CLAVE_DEP
			FROM DEPARTAMENTOS
	        WHERE NOMBRE=NOMBRE_DEP;/*ESTA CONSULTA DEVUELVE UNA TUPLA PORQUE NOMBRE ES AK*/
			IF VAR_CLAVE_DEP IS NOT NULL
					THEN  UPDATE EMPLEADOS
						SET  SALARIO=SALARIO+ SALARIO*PORCENTAJE/100
					WHERE DEPARTAMENTO=VAR_CLAVE_DEP;
                                               
			ELSE  SET OK=FALSE;
			INSERT INTO MENSAJES_DE_ERROR
			SELECT 'NO SE REALIZA LA OPERACIÓN , VALOR DE NOMBRE DE DEPARTAMENTO INCORRECTO '; 
		    END IF;          
			END CASE; 
           
END IF;             
END$$