/**  1 DISEÑAR PARA CADA DEPARTAMENTO  UNA VISTA CON LOS PROYECTOS LANZADOS POR CADA DEPARTAMENTO.
    TENDREMOS  entonces estas vistas: 
   VISTA_PROYECTOS_VENTAS, 
   VISTA_PROYECTOS_MARKETING, 
   VISTA_PROYECTOS_ADMINISTRACION 
   Y VISTA_PROYECTOS_PERSONAL 

  CADA JEFE DE  DEPARTAMENTO TENDRÁ ACCESO SÓLO A LA VISTA CORRESPONDIENTE A SU DEPARTAMENTO
  EN LA VISTA TENDREMOS LAS SIGUIENTES INFORMACIONES:
  CLAVE_PROYECTO, NOMBRE,  DIAS QUE FALTAN FINALIACIÓN, 
  PRIMER DIA DE TRABAJO, CANTIDAD DE EMPLEADOS TRABAJANDO, TOTAL_HORAS_TRABAJO, COSTE_ACTUAL_TRABAJO , PRESUPUESTO
  CANTIDAD DE EMPLEADOS DEL DEPARTAMENTO TRABAJANDO EN EL PROYECTO
  **/


 /**  CONTESTA : ¿ESTAS VISTAS SON VISTAS ACTUALIZABLES?
     ES DECIR, ¿DESDE LA VISTA PODEMOS ACTUALIZAR (OPERACIONES: INSERT INTO, DELETE FROM, UPDATE)
	 LAS TABLAS SUBYACENTES?
  
  
  /** 2 AHORA HACED CUATRO VISTAS MÁS, UNA PARA CADA DEPARTAMENTO
      LLAMADAS:
	  TRABAJO_PROYECTOS_VENTAS,
	  TRABAJO_PROYECTOS_MARKETING, 
	  TRABAJO_PROYECTOS_ADMINISTRACION 
	  Y 
      TRABAJO_PROYECTOS_PERSONAL
      
      CADA VISTA CONTENDRÁ INFORMACIÓN DE LOS PROYECTOS DE CADA DEPARTAMENTO, SÓLO LOS PROYECTOS
      LANZADOS POR CADA DEPARTAMENTO.
      
      CLAVE PROYECTO  CLAVE EMPLEADO FECHA_INICIO NUM_HORAS, PRECIO_HORA
      
      **/
      
      /** CONTESTA ¿ESTÁS VISTAS SON ACTUALIZABLES?
          PODREMOS MODIFICAR CUALQUIER  REGISTRO DE TRABAJO, CAMBIANDO NUMERO DE HORAS DE TRABAJO , EL PRECIO DE LA HORA
          PODREMOS INSERTAR Y ELIMINAR UN REGISTRO	
          PROBAD ESTAS OPERACIONES
      **/		