/**   PARA CADA PROYECTO QUE ESTÉ CON TRABAJO INICIADO, OBTENER:
     SU CLAVE, LA CANTIDAD DE EMPLEADOS TRABAJANDO EN ÉL, TOTAL HORAS DE TRABAJO,
     LA CANTIDAD DE EMPLEADOS SUPERVISADOS TRABAJANDO EN ÉL**/
     
   
   
   /*** MODIFICA LA CONSULTA ANTERIOR:
          PARA CADA PROYECTO QUE ESTÉ CON TRABAJO INICIADO, Y TENGA MÁS DE 3 EMPLEADOS TRABAJANDO
          OBTENER:
          SU CLAVE, LA CANTIDAD DE EMPLEADOS TRABAJANDO EN ÉL, TOTAL HORAS DE TRABAJO,
          LA CANTIDAD DE EMPLEADOS SUPERVISADOS TRABAJANDO EN ÉL**/
          
          
          
          
          
     
/**PARA CADA POYECTO QUE ESTÉ CON TRABAJO INICIADO, OBTENER:
   SU CLAVE, NOMBRE DE PROYECTO Y PRESUPUESTO, CANTIDAD DE EMPLEADOS TRABAJANDO EN EL PROYECTO,
   CANTIDAD DE EMPLEADOS QUE PERTENEZCAN AL MISMO DEPARTAMENTO QUE EL PROYECTO TRABAJANDO EN Él
   
   *****/