/*******A PARTIR DE AHORA
 NECESITAMOS PODER ALMACENAR MÁS 
 DE UNA DIRECCIÓN PARA NUESTROS 
 EMPLEADOS
 
 ***/
 /** ANALIZAMOS EL PROBLEMA
     ---> ERA UN ATRIBUTO PARA LA ENTIDAD EMPLEADO ---> OCUPA UNA COLUMNA EN LA TABLA EMPLEADOS
          SE HA CONVERTIDO
          EN UN ATRIBUTO MULTIVALUADO---> NECESITAMOS UNA NUEVA TABLA**/
          
          
   USE EMPRESA;
    DROP TABLE IF EXISTS EMPLEADOS_DIRECCIONES;
    CREATE TABLE EMPLEADOS_DIRECCIONES
        AS 
            SELECT  ID_EMPLEADO AS EMPLEADO,
                    DIRECCION AS DIRECCION 
                FROM EMPLEADOS;
                
   /** IMPORTANTE HEMOS VERIFICADO QUE COLUMNA DIRECCION ES OBLIGATORIA,
       SI FUESE OPTATIVA HARÍA FALTA EN SELECT  USAR CLÁUSULA WHERE DIRECCION IS NOT NULL**/
       
       
    /*NECESITAMOS AHORA REDEFINR LA TABLA  CREADA PARA  DEJARLA CORRECTAMENTE DEFINIDA**/
    
    
    ALTER TABLE EMPLEADOS_DIRECCIONES
       ADD FOREIGN KEY(EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
                                 ON DELETE CASCADE
                                 ON UPDATE CASCADE,
       ADD INDEX FK_EMPLEADO_DIRECCION(EMPLEADO);
       
       
     /** POR ÚLTIMO EN ESTE MOMENTO TENEMOS EL DATO DIRECCION DE CADA EMPLEADO ALMACENADO DOS VECES
         ESO SERÍA UN ERROR GRAVE!!!*/
         
         ALTER TABLE EMPLEADOS
            DROP COLUMN DIRECCION;
    
                
                