drop database if exists liga_baloncesto;
create database if not exists liga_baloncesto;
use liga_baloncesto;
DROP TABLE IF EXISTS LIGA_BALONCESTO.JUGADOR ;

CREATE TABLE IF NOT EXISTS LIGA_BALONCESTO.JUGADOR (
  ID_JUGADOR INT UNSIGNED NOT NULL AUTO_INCREMENT,
  DNI VARCHAR(9) NOT NULL,
  NOMBRE_APELLIDOS VARCHAR(30) NOT NULL,
  NACIONALIDAD ENUM('ESPAÑOLA', 'INGLESA', 'YUGOSLAVA', 'AMERICANA', 'JAMAICANA') NULL DEFAULT NULL,
  DORSAL INT NULL DEFAULT NULL,
  EQUIPO INT UNSIGNED NULL,
  PRIMARY KEY (ID_JUGADOR),
  UNIQUE INDEX DNI_UNIQUE (DNI),
  INDEX FK_EQUIPO_FICHADO (EQUIPO),
  UNIQUE INDEX DORSAL (DORSAL ASC, ID_JUGADOR)
  
)ENGINE = InnoDB;

DROP TABLE IF EXISTS LIGA_BALONCESTO.EQUIPO ;

CREATE TABLE IF NOT EXISTS LIGA_BALONCESTO.EQUIPO (
  ID_EQUIPO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE_EQUIPO VARCHAR(15) NOT NULL,
  NOMBRE_ENTRENADOR VARCHAR(55) NULL DEFAULT NULL,
  NOMBRE_CANCHA VARCHAR(30) NOT NULL,
  POBLACION VARCHAR(25) NOT NULL,
  AÑO_FUNDACION YEAR NULL DEFAULT NULL,
  CAPITAN INT UNSIGNED NOT NULL,
  PRIMARY KEY (ID_EQUIPO),
  UNIQUE INDEX NOMBRE_EQUIPO_UNIQUE (NOMBRE_EQUIPO),
  UNIQUE INDEX NOMBRE_CANCHA_UNIQUE (NOMBRE_CANCHA ) ,
  INDEX FK_CAPITAN (CAPITAN),
  CONSTRAINT FK_CAPITAN
    FOREIGN KEY (CAPITAN)
    REFERENCES LIGA_BALONCESTO.JUGADOR (ID_JUGADOR)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
    )ENGINE = InnoDB;
alter table liga_baloncesto.jugador 
add CONSTRAINT FK_EQUIPO_FICHADO
    FOREIGN KEY (EQUIPO)
    REFERENCES LIGA_BALONCESTO.EQUIPO (ID_EQUIPO)
    ON DELETE CASCADE
    ON UPDATE CASCADE;
DROP TABLE IF EXISTS LIGA_BALONCESTO.PARTIDOS ;

CREATE TABLE IF NOT EXISTS LIGA_BALONCESTO.PARTIDOS (
  ID_PARTIDO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  EQUIPO_LOCAL INT UNSIGNED NOT NULL,
  EQUIPO_VISITANTE INT UNSIGNED NOT NULL,
  FECHA_PARTIDO DATE NULL DEFAULT NULL,
  PUNTOS_LOCAL INT UNSIGNED NOT NULL DEFAULT 0,
  PUNTOS_VISITANTE INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (ID_PARTIDO),
  INDEX FK_EQUIPO_VISITANTE (EQUIPO_VISITANTE),
  INDEX FK_EQUIPO_LOCAL (EQUIPO_LOCAL),
  UNIQUE INDEX PARTIDO_UNICO (EQUIPO_LOCAL,EQUIPO_VISITANTE),
  CONSTRAINT FK_EQUIPO_LOCAL
    FOREIGN KEY (EQUIPO_LOCAL)
    REFERENCES LIGA_BALONCESTO.EQUIPO (ID_EQUIPO)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT FK_EQUIPO_VISITANTE
    FOREIGN KEY (EQUIPO_VISITANTE)
    REFERENCES LIGA_BALONCESTO.EQUIPO (ID_EQUIPO)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;
