/*** Enunciado: Modificación del modelo ****/ 


/*******A PARTIR DE AHORA
 NECESITAMOS PODER ALMACENAR EN LA BASE DE DATOS MÁS 
 DE UNA DIRECCIÓN PARA NUESTROS EMPLEADOS, NO PERDER, POR SUPUESTO, LA INFORMACIÓN ALMACENADA
 HASTA EL MOMENTO.
 
 ***/
 USE EMPRESA;
 
  /** 1º SOLUCION**/
          
   CREATE TABLE  IF NOT EXISTS EMPLEADOS_DIRECCIONES
   (
      EMPLEADO INTEGER UNSIGNED NOT NULL,
      DIRECCION  VARCHAR(50) NOT NULL,
      PRIMARY KEY (EMPLEADO,DIRECCION),
      FOREIGN KEY (EMPLEADO)REFERENCES EMPLEADOS(ID_EMPLEADO)
                           ON DELETE CASCADE
                           ON UPDATE CASCADE,
      INDEX FK_EMPLEADO_DIRECCION(EMPLEADO)                     
     
   
   )ENGINE INNODB;
   
   /** YA TENEMOS EL ESPACIO PREPARADO PARA ALMACENAR LA NUEVA INFORMACIÓN...*/
   /** COPIAMOS LAS DIRECCIONES QUE TENEMOS HASTA AHORA, UNA POR EMPLEADO..*/
   INSERT INTO EMPLEADOS_DIRECCIONES
    (EMPLEADO,DIRECCION) 
    SELECT  ID_EMPLEADO,DIRECCION
        FROM EMPLEADOS;
     /** COMO   LA COLUMNA DIRECCION EN EMPLEADOS ES OBLIGATORIA
          POR ESO ESTA CONSULTA NO LLEVA WHERE, ES IMPORTANTE VERIFICAR SI COLUMNA ES NOT NULL/NULL*/
  /** POR FIN,  AHORA ELIMINAMOS COLUMNA DIRECCION EN TABLA EMPLEADOS**/
  ALTER TABLE empleados 
      DROP COLUMN DIRECCION;
 
/*2º SOLUCION

AQUI CREAMOS LA TABLA EN LA CUAL METEREMOS LAS MULTIPLES DIRECIONES*/
  DROP TABLE IF EXISTS EMPLEADOS_DIRECCIONES;
    CREATE TABLE EMPLEADOS_DIRECCIONES
        AS 
            SELECT  ID_EMPLEADO AS EMPLEADO,
                    DIRECCION AS DIRECCION 
                FROM EMPLEADOS;
                
   /** IMPORTANTE HEMOS VERIFICADO QUE COLUMNA DIRECCION ES OBLIGATORIA,
       SI FUESE OPTATIVA HARÍA FALTA EN SELECT  USAR CLÁUSULA WHERE DIRECCION IS NOT NULL**/
       
       
    /*NECESITAMOS AHORA REDEFINR LA TABLA  CREADA PARA  DEJARLA CORRECTAMENTE DEFINIDA**/
    
    
    ALTER TABLE EMPLEADOS_DIRECCIONES
       ADD FOREIGN KEY(EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
                                 ON DELETE CASCADE
                                 ON UPDATE CASCADE,
       ADD INDEX FK_EMPLEADO_DIRECCION(EMPLEADO);
       
       
     /** POR ÚLTIMO EN ESTE MOMENTO TENEMOS EL DATO DIRECCION DE CADA EMPLEADO ALMACENADO DOS VECES
         ESO SERÍA UN ERROR GRAVE!!!*/
         
         ALTER TABLE EMPLEADOS
            DROP COLUMN DIRECCION;
 