/*    EJERCICIO PROPUESTO 1***/

# **/****** ENUNCIADO  EJERCICIO 2 TRANSACCIONES
/* todas estas operaciones deseamos  que sean englobadas en una sola operación **********
# 1.  CREAMOS UN NUEVO DEPARTAMENTO EN LA EMPRESA 
        DE NOMBRE MARKETING 2, EL DIRECTOR SERÁ EL EMPLEADO DE CLAVE 8
       , CON PRIMA DE IMPORTE 1500, Y CON  CARGO DESDE FECHA ACTUAL
# 2.  A ÉL ( EL NUEVO DIRECTOR)  EMPLEADO DE CLAVE 8 LE ASIGNAMOS 
       COMO DEPARTAMENTO EL NUEVO DEPARTAMENTO  Y  UN  SALARIO DE 1800
#  3. ESTE NUEVO DEPARTAMENTO ASUME TODOS LOS PROYECTOS LANZADOS POR EL DEPARTAMENTO  DE CLAVE 3
#  4. PASAN A FORMAR PARTE DE ESTE NUEVO DEPARTAMENTO TODOS LOS EMPLEADOS DEL DEPARTAMENTO 3
#  5  SE ELIMINA EL DEPARTAMENTO DE CLAVE 3
# REALIZAR TODAS ESTAS ÓRDENES EN UNA TRANSACCIÓN.
FIJARSE  EL ORDEN EN SE REALIZAN LAS OPERACIONES ES IMPORTANTE !!
#*********************************************************************/

START TRANSACTION;

/*1*/

INSERT INTO DEPARTAMENTOS 
(NOMBRE,DIRECTOR,PRIMA_SUELDO,FECHA_INICIO)
value
('MARKETING 2',8,1500.0,current_date());

/*2*/

SELECT NUMERO INTO @DATO
	FROM DEPARTAMENTOS
    WHERE NOMBRE='MARKETING 2';

UPDATE EMPLEADOS
	SET DEPARTAMENTO=@DATO, SALARIO=1800.0
    WHERE ID_EMPLEADO=8;
    
/*3*/

UPDATE PROYECTOS
	SET DEPARTAMENTO=@DATO
    WHERE DEPARTAMENTO=3;
    
/*4*/

UPDATE EMPLEADOS
	SET DEPARTAMENTO=@DATO
    WHERE DEPARTAMENTO=3;
    
/*5*/

DELETE FROM DEPARTAMENTOS 
	WHERE NUMERO=3;



COMMIT;

