 /************************************************************************************************
/***SUPONER AHORA ESTAS ÓRDENES:
       1.   MODIFICAR  AL DIRECTOR DEL DEPARTAMENTO DE VENTAS
            EL NUEVO DIRECTOR SERÁ EL EMPLEADO DE CLAVE 10, HASTA 
            AHORA CONSTABA COMO DIRECTOR DE ESE DEPARTAMENTO  EL EMPLEADO DE CLAVE 2
        2. A CONTINUACIÓN, DAMOS DE BAJA O ELIMINAMOS DE LAS BASE DE DATOS
           AL EMPLEADO DE CLAVE 2
        3. ESTAS DOS OPERACIONES SE TIENE QUE REALIZAR EN ESTE ORDEN
           Y LAS UNIMOS EN UNA TRANSACCIÓN----> COSTRUÍMOS
            PARA TODOS LOS DEMÁS USUARIOS DE LA BASE DE DATOS
            UNA OPERACIÓN ATÓMICA CON ESTAS DOS ÓRDENES
            Y TODAS SUS CONSECUENCIAS INTERNAS
            (BORRADO EN CASCADA EN EMPLEADOS-PROYECTOS
            Y EN FAMILIARES)
            **/
            
    START TRANSACTION; 
      UPDATE DEPARTAMENTOS 
        SET DIRECTOR=10
        WHERE DIRECTOR=2; /*SELECCIONA UNA TUPLA LA QUE AK DIRECTOR=2*/
      
     /* tAMBIÉN ASÍ 
        UPDATE DEPARTAMENTOS 
        SET DIRECTOR=10
        WHERE NOMBRE='VENTAS';/*SELECCIONA UNA TUPLA LA QUE AK NOMBRE ES VENTAS*/  
            
      DELETE FROM EMPLEADOS 
        WHERE ID_EMPLEADO=2;
        
        
       
         /** SE ELIMNAN EN CASCADA TODAS LAS TUPLAS DE LA TABLA E_P Y DE LA TABLA FAMILIARES
               DONDE ESTA TUPLA ESTÁ REFERENCIADA,
               SI EN LA TABLA EMPLEADOS HAY TUPLAS QUE LA REFERENCIAN EN LA COLUMNA SUPERVIOSR, ENTONCES SE MODIFICARÁN
               CON VALOR NULL
               **/
     COMMIT;        
     
     