/*    EJERCICIO PROPUESTO 1***/

# **/****** ENUNCIADO  EJERCICIO 2 TRANSACCIONES
/* todas estas operaciones deseamos  que sean englobadas en una sola operación **********
# 1.  CREAMOS UN NUEVO DEPARTAMENTO EN LA EMPRESA 
        DE NOMBRE MARKETING 2, EL DIRECTOR SERÁ EL EMPLEADO DE CLAVE 8
       , CON PRIMA DE IMPORTE 1500, Y CON  CARGO DESDE FECHA ACTUAL
# 2.  A ÉL ( EL NUEVO DIRECTOR)  EMPLEADO DE CLAVE 8 LE ASIGNAMOS 
      COMO DEPARTAMENTO EL NUEVO DEPARTAMENTO  EL   Y  UN  SALARIO DE 1800
#  3. ESTE NUEVO DEPARTAMENTO ASUME TODOS LOS PROYECTOS LANZADOS POR EL DEPARTAMENTO  DE CLAVE 3
#  4. PASAN A FORMAR PARTE DE ESTE NUEVO DEPARTAMENTO TODOS LOS EMPLEADOS DEL DEPARTAMENTO 3
#  5  SE ELIMINA EL DEPARTAMENTO DE CLAVE 3
# REALIZAR TODAS ESTAS ÓRDENES EN UNA TRANSACCIÓN.
FIJARSE  EL ORDEN EN SE REALIZAN LAS OPERACIONES ES IMPORTANTE !!
#*********************************************************************/


START TRANSACTION;
  INSERT INTO DEPARTAMENTOS 
  (NOMBRE,DIRECTOR,PRIMA_SUELDO,FECHA_INICIO)
  VALUES
  ( 'MARKETING 2',
     8,
     1500.0,
     CURRENT_DATE()
  );
/**2*/
  SELECT  NUMERO INTO @DATO
     FROM DEPARTAMENTOS
     WHERE NOMBRE='MARKETING 2'; /*OTRA AK ES DIRECTOR WHERE DIRECTOR=8*/
 
 UPDATE EMPLEADOS  
    SET  DEPARTAMENTO=@DATO, SALARIO=1800.0
    WHERE ID_EMPLEADO=8;
    
/**  O TAMBIÉN DE OTRA FORMA
 UPDATE EMPLEADOS  
    SET  DEPARTAMENTO=( SELECT  NUMERO 
                          FROM DEPARTAMENTOS
                           WHERE NOMBRE='MARKETING 2'
                       ),
         SALARIO=1800.0
    WHERE ID_EMPLEADO=8;
    **/
 
/**3**/
  UPDATE PROYECTOS
      SET DEPARTAMENTO=@DATO
   WHERE DEPARTAMENTO=3;  /*SELECCIONO TODOS LOS PROYECTOS DONDE DEPARTAMENTO=3*/    
 
 /**4**/
   UPDATE EMPLEADOS
      SET DEPARTAMENTO=@DATO
   WHERE DEPARTAMENTO=3; /** PUEDE SELECCIONAR CERO O N TUPLAS*/
   
   /**5*/
   
      DELETE FROM DEPARTAMENTOS
        WHERE NUMERO=3;
COMMIT;

