/*** 1º
    INFORME PARA CADA DIRECTOR, SU CLAVE
        CUANTOS PROYECTOS TRABAJA Y TOTAL HORAS QUE  TRABAJA
   (SOLO INTERESAN DIRECTORES QUE ESTÁN TRABAJANDO EN AlGÚN PROYECTO*/   
   
 /** OBTENER UNA TABLA CONESTOS DATOS**/
     SELECT EP.EMPLEADO AS CLAVE_DIRECTOR,
           COUNT(*) AS CANTIDAD_PROYECTOS,
           SUM(NUM_HORAS) AS TOTAL_HORAS
		FROM EMPLEADOS_PROYECTOS AS EP
        WHERE EMPLEADO IN (
                           SELECT DIRECTOR 
							FROM DEPARTAMENTOS
                            )
	    GROUP BY EP.EMPLEADO;
 /** DESPUES,
    SOBRE ESA INFORMACIÓN
    CÚAL ES LA MAYOR CANTIDAD DE PROYECTOS EN LOS QUE TRABAJA  UN DIRECTOR Y 
    CUÁL ES LA MAYOR CANTIDAD DE HORAS DE TRABAJO EN LOS DISTINTOS PROYECTOS
    QUE HACE UN DIRECTOR
    **/
    SELECT MAX(CANTIDAD_PROYECTOS) AS MAX_CANTIDAD_PROYECTOS,
		   MAX(TOTAL_HORAS) AS MAX_CANTIDAD_HORAS_PROYECTOS
		FROM(
	        SELECT EP.EMPLEADO AS CLAVE_DIRECTOR,
                   COUNT(*) AS CANTIDAD_PROYECTOS,
                   SUM(NUM_HORAS) AS TOTAL_HORAS
				FROM EMPLEADOS_PROYECTOS AS EP
				WHERE EMPLEADO IN (
                                   SELECT DIRECTOR 
									FROM DEPARTAMENTOS
                                  )
	           GROUP BY EP.EMPLEADO
             )AS TABLA_DERIVADA;
    
   