/*obtener para cada empleado su nombre
y salario y nombre de su departamento*/

SELECT E.NOMBRE,E.SALARIO
	FROM EMPLEADOS AS E;
    
SELECT E.NOMBRE,
       E.SALARIO,
       D.NOMBRE AS DEPARTAMENTO
	FROM EMPLEADOS AS E INNER JOIN DEPARTAMENTOS AS D
						  ON E.DEPARTAMENTO=D.NUMERO;
                          
/*obtener para cada empleado su nombre
y salario y nombre Y SALARIO DE SU SUPERVISOR*/

SELECT *
	FROM EMPLEADOS AS E INNER JOIN EMPLEADOS AS D
                                ON E.SUPERVISOR=D.ID_EMPLEADO;

SELECT E.NOMBRE AS EMPLEADOS,
       E.SALARIO AS SALARIO_SUPERVISADO,
       D.NOMBRE AS NOMBRE_SUPERVISOR,
       D.SALARIO- E.SALARIO AS SALARIO_SUPERVISOR
	FROM EMPLEADOS AS E INNER JOIN EMPLEADOS AS D
                                ON E.SUPERVISOR=D.ID_EMPLEADO;
                                
/*obtener para cada PROYECTO su nombre
y PRESUPUESTO y nombre DEPARTAMENTO Y CLAVEDIRECTORT DEPARTASMENTO
*/

SELECT E.NOMBRE AS PROYECTOS,
       E.PRESUPUESTO AS PRESUPUESTO_PROYECTO,
       D.NOMBRE AS NOMBRE_DEPARTAMENTO,
       D.DIRECTOR AS ID_DIRECTOR
	FROM PROYECTOS AS E INNER JOIN DEPARTAMENTOS AS D
                                ON E.DEPARTAMENTO=D.NUMERO;
                                
 /*obtener para cada EMPLEADO su nombre
y PRESUPUESTO y nombre DEPARTAMENTO Y NOMBRE YSALARIO  DIRECTOR DEPARTASMENTO
*/                               

SELECT E.NOMBRE AS EMPLEADOS,
       E.SALARIO AS SALARIO_SUPERVISADO,
       ED.NOMBRE AS NOMBRE_DIRECTOR,
       ED.SALARIO AS SALARIO_DIRECTOR
	FROM EMPLEADOS AS E INNER JOIN DEPARTAMENTOS AS D 
							ON E.DEPARTAMENTO=D.NUMERO
								INNER JOIN EMPLEADOS AS ED
									ON D.DIRECTOR=ED.ID_EMPLEADO;
                                    
                                    
                                    
                                    
SELECT * 
	FROM PROYECTOS AS P INNER JOIN EMPLEADOS_PROYECTOS AS D
							ON P.iD_PROYECTO=D.PROYECTO
	GROUP BY P.ID_PROYECTO;
    
SELECT P.ID_PROYECTO AS ID_PROYECTO,
       P.NOMBRE AS PROYECTO,
       COUNT(*) AS CANTIDAD_EMPLEADOS_PROYECTOS,
       SUM(NUM_HORAS) AS TOTAL_HORAS
	FROM PROYECTOS AS P INNER JOIN EMPLEADOS_PROYECTOS AS D
							ON P.iD_PROYECTO=D.PROYECTO
	GROUP BY P.ID_PROYECTO;