/*****
    cantidad de empleados que están supervisados,
    su salario medio y el salario más alto 
    de los supervisados
    **/
    
    SELECT AVG(SALARIO)AS SALARIO_MEDIO,
		   COUNT(*) AS CANTIDAD_EMPLEADOS,
           MAX(SALARIO) AS SALARIO_MAXIMO
		from empleados
        WHERE SUPERVISOR;
      
      
   /**** CUANTOS EMPLEADOS ESTÁN TRABAJANDO EN LOS
        PROYECTOS DE CLAVES 2,3 4, Y 5**/
        
SELECT COUNT(distinct EMPLEADO) AS CANTIDAD_EMPLEADOS
	FROM EMPLEADOS_PROYECTOS
    WHERE PROYECTO IN(2,3,4,5);
          
        /*** LISTA DE CLAVES PRIMARIAS DE LOS EMPLEADOS
             QUE SON DIRECTORES ***/
             
SELECT DIRECTOR
	FROM DEPARTAMENTOS;
                
      /***PROHIBIDO,NO USO DISTINCT !!! 
          PORQUE COLUMNA DIRECTOR TIENE RESTRICCIÓN DE UNICIDAD
          SI LA RELACION TENER DIRECTOR FUESE (1,N) LA COLUMNA DIRECTOR FK NO TENRIA RESTRINCION DE UNICIDAD
          SU INDICE FK DIRECTOR SERIA DE TIPO INDEX ENTONCES LA CONSULTA SERIA ASI
          SELECT DISTINCT DIRECTOR
			  FROM DEPARTAMWENTOS;**/
 
 
 /** LISTA DE CLAVES PRIMARIAS DE LOS EMPLEADOS
           QUE SON SUPERVISORES DE OTROS**/
             
SELECT  DISTINCT SUPERVISOR
	FROM EMPLEADOS
    WHERE SUPERVISOR IS NOT NULL;
    

             
 /* EL INDICE FK_SUPERVISOR NO ES ÚNICO
   ---> U SUPERVISOR PUEDE ESTAR REPETIDO 
   **/
   
   
   /***** GROUP BY COLUMNA**/
   
   
/**** PARA CADA DEPARTAMENTO DE LA EMPRESA
OBTENER CANTIDAD DE EMPLEADOS QUE TIENE
Y SU SALARIO MEDIO
***/
SELECT  DEPARTAMENTO AS DEPARTAMENTO,
		COUNT(*) AS CANTIDAD_EMPLEADOS,
		AVG(SALARIO) AS CANTIDAD_MEDIA
	FROM EMPLEADOS
    GROUP BY DEPARTAMENTO;

   
   /**CADA GRUPO SON LOS EMPLEADOS
   DE UN DEPARTAMENTO
   **/

/** CLAVES DE LOS DISTINTOS DEPARTAMENTOS
     DE LA EMPRESA**/
  
SELECT NUMERO
	FROM DEPARTAMENTOS;
  
  /** NO TIENES ACCESO A LA TABLA DEPARTAMENTOS
     SI TENGO ACCESO A EMPLEADOS**/
SELECT DISTINCT DEPARTAMENTO
	FROM EMPLEADOS;
 
  /** NO USAR GROUP BY PARA ESTA CONSULTA
  ----> NO PIDEN NINGUN DATO DE GRUPO**/
  
/** ESTA CONSULTA PARA LOS EMPLEADOS DEL DEPARTAMENTO 
   DE CLAVE 2**/
   
   
   
      
/*** PARA CADA DEPARTAMENTO
  OBTENER LA CANTIDAD DE PROYECTOS
  QUE TIENE LANZADO, EL TOTAL DE SUS PRESUPUESTOS
  Y LA FECHA MÁS ANTIGUA DE PROYECTO
  **/
  
SELECT DEPARTAMENTO AS DEPARTAMENTO,
	   COUNT(*) AS CANTIDAD_PROYECTOS_LANZADOS,
	   SUM(PRESUPUESTO) AS TOTAL_PRESUPUESTO,
       MIN(FECHA_INICIO)
	FROM PROYECTOS
	GROUP BY DEPARTAMENTO;
  
  
  /**PARA CADA SUPERVISOR OBTENER
     CANTIDAD DE EMPLEADOS SUPERVISADOS
     SALARIO MEDIO DE SUS SUPERVISADOS
     **/
     
SELECT SUPERVISOR AS SUPERVISOR,
	   AVG(SALARIO) AS SALARIO_MEDIO_SUPERVISADOS,
       COUNT(SUPERVISOR) AS EMPLEADOS_SUPERVISADOS 
	FROM EMPLEADOS
    WHERE SUPERVISOR IS NOT NULL
    GROUP BY SUPERVISOR;
        
 /*SE FORMAN TANTOS GRUPOS COMO VALORES DISTINTOS
   HAY EN LA COLUMNA SUPRVISOR
   --- SE FORMARÍA 1 GRUPO PARA LOS NULL
   SI LO QUITO
   HAY TANTOS GRUPOS COMO SUPERVISORES **/

/*LISTA DE NOMBRES DE LOS DIRECTORES*/

SELECT NOMBRE
	FROM EMPLEADOS
    WHERE ID_EMPLEADO IN (
						   SELECT DIRECTOR
							 FROM DEPARTAMENTOS);
     
     
     
    /*LISTA DE NOMBRES DE LOS SUPERVISADOS**/ 

SELECT NOMBRE
	FROM EMPLEADOS
    WHERE SUPERVISOR IS NOT NULL;
     
  /**** OBTENER PARA CADA DEPARTAMENTO
    CANTIDAD DE EMPLEADOS SUPERVISADOS  QUE TIENE
    Y SALARIO MEDIO DE LOS SUPERVISADOS DEL DEPARTAMENTO
    **/
    
select DEPARTAMENTO AS DEPARTAMENTO,
       count(*) as empleados_supervisados_por_departamento,
	   avg(salario) as media_salario
	from empleados
	where supervisor is not null
	group by departamento;/*lo agrupa por departamento por lo tanto esto al final
    nos mostrara lo que pide el enunciado*/
    
/****** POR CADA DEPARTAMENTO OBTENER:
      CANTIDAD DE EMPLEADOS,
      CANTIDAD DE EMPLEADOS SUPERVISADOS,
      CANTIDAD DE EMPLEAODS SIN SUPERVISAR,
      SALARIO MEDIO DEL DEPARTAMENTO 
  **/
select DEPARTAMENTO AS DEPARTAMENTO,
       count(*) as CANTIDAD_empleados,
	   COUNT(SUPERVISOR) AS CANTIDAD_SUPERVISADOS,
       COUNT(*)-COUNT(SUPERVISOR) AS CANTIDAD_DE_NO_SUPERVISADFOS,
	   avg(salario) as media_salario
	from empleados
	group by departamento;
       
/*****  PARA LOS DEPARTAMENTOS
        QUE TENGAN MÁS DE 2 EMPLEADOS , OBTENER:
        SALARIO MEDIO DEL DEPARTAMENTO, CANTIDAD DE SUPERVISADOS
        Y MAYOR SALARIO
   ***/
   

                         
   
 /*** CADA GRUPO SON LOS EMPLEADOS DE CADA DEPARTAMENTO**/  
   
  /** OBTENER PARA CADA PROYECTO:
      SU CLAVE DE PROYECTO,
       LA CANTIDAD DE EMPLEADOS TRABAJANDO EN ÉL, 
      TOTAL HORAS DE TRABAJO 
      **/
      
SELECT PROYECTO AS ID_PROYECTO,
       SUM(NUM_HORAS) AS NUMERO_DE_HORAS_TOTAL,
       COUNT(*) AS NUMERO_EMPLEADOS
	FROM EMPLEADOS_PROYECTOS
    GROUP BY PROYECTO;
    /*** CADA GRUPO SON LOS REGISTROS DE TRABAJO DE CADA PROYECTO***/
     /*** HABRÁ TANTOS GRUPOS COMO PROYECTOS TRABAJANDO...*/
     /**** TAMAÑO DE TABLA PROYECTOS NO TIENE PORQUE SER = NÚMERO DE GRUPOS**/
     
     
  /** OBTENER PARA CADA EMPLEADO:
      SU CLAVE DE EMPLEADO,
       LA CANTIDAD DE PROYECTOS TRABAJANDO EN ÉL, 
      TOTAL HORAS DE TRABAJO 
      **/     
SELECT EMPLEADO AS ID_EMPLEADO,
       SUM(NUM_HORAS) AS NUMERO_DE_HORAS_TOTAL,
       COUNT(*) AS NUMERO_PROYECTOS
	FROM EMPLEADOS_PROYECTOS
    GROUP BY EMPLEADO;
    
/*CUANTOS EMPLEADOS HAY EN LA ERMPRESA*/
SELECT COUNT(*) AS EMPLEADOS_EN_TOTAL
      FROM EMPLEADOS;
      
/*CUANTOS EMPLEADOS ESTAN TRABAJANDO EN ALGUN PROYECTO*/
     
SELECT COUNT(DISTINCT EMPLEADO) AS CANTIDAD_EMPLEADOS_EN_PROYECTOS
	FROM EMPLEADOS_PROYECTOS;
    
/*OBTENER CLAVE EMPLEADO Y CANTIDAD HORAS DE TRABAJO DE LOS 
DISTINTOD PROYECTOS Q TRABAJEN MAS DE 50 HORAS EN LOS DISTINTOD PROYECTO*/

SELECT EMPLEADO AS EMPLEADO,
       SUM(NUM_HORAS) AS TOTAL_HORAS_TRABAJO
	FROM EMPLEADOS_PROYECTOS
    GROUP BY EMPLEADO
    HAVING SUM(NUM_HORAS)>50;

   /** PARA LOS PROYECTOS QUE HAYAN COMENZADO SU TRABAJO
       HACE MÁS DE 30 DIAS, OBTENER: SU CLAVE, CANTIDAD 
       DE EMPLEADOS QUE ESTÁN TRABAJANDO EN ÉL
       **/
       
SELECT COUNT(*) AS CANTIDAD_EMPLEADOS
	FROM EMPLEADOS_PROYECTOS
    GROUP BY PROYECTO
    HAVING DATEDIFF((CURRENT_DATE),MIN(FECHA_INICIO))>30;

  
/*******************************************************************/      
      
 /**OBTENER  LAS CLAVES DE LOS EMPLEADOS QUE ESTÁN
    TRABAJANDO EN MÁS DE 3 PROYECTOS DISTINTOS Y CANTIDAD DE PROYECTOS QUE TRABAJAN
  **/
    
SELECT empleado as id_empleado,
	   COUNT(*) CANTIDAd_PROYECTOS_TRABAJAN
	FROM EMPLEADOS_PROYECTOS
    GROUP BY EMPLEADO
    HAVING COUNT(*)>3;
    
   /*** CLAVES DE  EMPLEADOS**/
   
SELECT ID_EMPLEADO
	FROM EMPLEADOS;
   
   /*** CLAVES DE EMPLEADOS QUE TRABAJAN EN ALGÚN PROYECTO**/
   
SELECT DISTINCT EMPLEADO
	FROM EMPLEADOS_PROYECTOS;
   
              /****NO HACE FALTA PARA ESTA CONSULTA USAR GROUP BY
              PORQUE NO HAN PEDIDO NINGUN DATO DE AGRUPAMIENTO**/
   
  /********************************************************/ 

/**** PARA LOS EMPLEADOS QUE ESTÉN TRABAJANDO
EN MÁS DE 3 PROYECTOS, SU CLAVE ,CANTIDAD DE PROYECTOS
   Y TOTAL HORAS DE TRABAJO QUE REALIZAN**/  
   
SELECT empleado as id_empleado,
	   COUNT(*) CANTIDAd_PROYECTOS_TRABAJAN,
       SUM(NUM_HORAS) AS TOTAL_HORAS_TABAJADOS
	FROM EMPLEADOS_PROYECTOS
    GROUP BY EMPLEADO
    HAVING COUNT(*)>3;
   
/**** PARA LOS EMPLEADOS QUE ESTÉN TRABAJANDO
EN MÁS DE 3 PROYECTOS,  y hayan comenzado a trabajar
  en algún proyecto antes del día 12 de enero del 2017,
  SU CLAVE ,CANTIDAD DE PROYECTOS
   Y TOTAL HORAS DE TRABAJO QUE REALIZAN**/  

SELECT EMPLEADO AS ID_EMPLEADO,
       COUNT(*) AS CANTIDAD_PROYECTOS,
       SUM(NUM_HORAS) AS CANTIDAD_HORAS_TRABAJADAS
	FROM EMPLEADOS_PROYECTOS
    WHERE FECHA_INICIO>2017-01-12
    GROUP BY EMPLEADO
    HAVING COUNT(*)>3;
   
   
   
   
/***OBTENER PARA LOS EMPLEADOS :
   
   SU CLAVE, CANTIDAD DE PROYECTOS EN LOS QUE TRABAJAN
   Y TOTAL HORAS DE TRABAJO EN LOS DISTINTOS PROYECTOS
   
   EN EL INFORME SÓLO SE TIENE EN CUENTA LOS REGISTRO DE TRABAJO
    QUE HAYAN COMENZADO DESPUES DE 2017-08-20*/
   
   
/*** PARA CADA SUPERVISOR
     CANTIDAD DE EMPLEADOS SUPERVISADOS**/
    
SELECT SUPERVISOR AS ID_SUPERVISOR,
       COUNT(*) AS EMPLEADOS_SUPERVISADOS
	FROM EMPLEADOS
    WHERE SUPERVISOR
    GROUP BY SUPERVISOR;
     
   /***** ATENCIÓN , FIJARSE EN COMO SE DISEÑA**/  
   /**** from ? empleados porque la relación ser supervisor o estar
        supervisado está almacenada en empleados
  
  
  /**AÑADE A ESTE INFORME, 
  EL SALARIO MEDIO DE LOS SUPERVISADOS DE CADA SUPERVISOR**/
  
  SELECT SUPERVISOR AS ID_SUPERVISOR,
         COUNT(*) AS EMPLEADOS_SUPERVISADOS,
         AVG(SALARIO) AS SALARIO_SUPERVISADOS
	FROM EMPLEADOS
    WHERE SUPERVISOR
    GROUP BY SUPERVISOR;
 
  /***AÑADE AL INFORME ANTERIOR
      CANTIDAD DE DEAPRTAMENTOS A LOS QUE 
      PERTENECEN LOS SUPERVISADOS DE CADA SUPERVISOR**/
    
    SELECT SUPERVISOR AS ID_SUPERVISOR,
           COUNT(*) AS EMPLEADOS_SUPERVISADOS,
           AVG(SALARIO) AS SALARIO_SUPERVISADOS,
           COUNT(DISTINCT DEPARTAMENTO) AS CANTIDAD_DEPARTAMENTOS_SUPERVISADOS
	FROM EMPLEADOS
    WHERE SUPERVISOR
    GROUP BY SUPERVISOR;


  /*** PARA LOS  SUPERVISORES CON MÁS DE 3 SUPERVISADOS,
       OBTENER SU CLAVE Y
      CANTIDAD DE EMPLEADOS SUPERVISADOS**/  
     
   SELECT SUPERVISOR AS ID_SUPERVISOR,
         COUNT(*) AS EMPLEADOS_SUPERVISADOS
	FROM EMPLEADOS
    WHERE SUPERVISOR
    GROUP BY SUPERVISOR
    HAVING COUNT(*)>3;  
     
  /*** CUÁNTOS SUPERVISORES HAY ???**/
  
SELECT COUNT(DISTINCT SUPERVISOR) CANTIDAD_SUPERVISORES
	FROM EMPLEADOS
    WHERE SUPERVISOR;
     
   /*** CLAVES DE  LOS SUPERVISORES?**/  
     
   SELECT DISTINCT SUPERVISOR AS ID_SUPERVISOR
	FROM EMPLEADOS
    WHERE SUPERVISOR; 
     
       /*** CUÁNTOS SUPERVISADOS HAY ???**/
       
SELECT COUNT(*) AS CANTIDAD_SUPERVISADOS
	FROM EMPLEADOS
    WHERE SUPERVISOR;
     
   /*** OBTENER INFORME DE:
        CLAVE DE CADA SUPERVISOR Y MAYOR SALARIO DE SUS
        SUPEVISADOS, CANTIDAD DE SUPERVISADOS.
        EN EL INFORME 
        NO SE TIENE EN CUENTA A LOS SUPERVISADOS DEL DEPARTAMENTO 3**/
       
SELECT SUPERVISOR AS ID_SUPERVISOR,
       COUNT(*) AS CANTIDAD_SUPERVISADOS,
	   MAX(SALARIO) AS MAYOR_SALARIO_SUPERVISADOS
	FROM EMPLEADOS
    WHERE SUPERVISOR 
           AND DEPARTAMENTO !=3
    GROUP BY SUPERVISOR;
    
        
    /****    
        
        
       /**** CONDICIÓN DE GRUPO ??
                CONDICIÓN DE TUPLA??***/
                
                
                    
        
        /* CADA GRUPO SON LOS EMPLEADOS SUPERVISADOS POR CADA SUPERVISOR **/    
        
      /****DE CADA PROYECTO,
      OBTENER UN INFORME CON:
        CLAVE DEL PROYECTO,
        CANTIDAD DE EMPLEADOS TRABAJANDO,
        EL TOTAL HORAS DE TRABAJO QUE SE REALIZAN EN CADA PROYECTO,
        LA FECHA MÁS ANTIGÜA DE COMIENZO DE TRABAJO, 
        CUÁNTOS DÍA LLEVAMOS TRABAJANDO EN CADA PROYECTO,
        EL INFORME LO QUEREMOS ORDENADO POR CANTIDAD DE EMPLEADOS
        TRABAJANDO DE MAYOR A MENOR
        ***/
        
SELECT PROYECTO AS ID_PROYECTO,
       COUNT(*) AS CANTIDAD_EMPLEADOS_EN_PROYECTO,
       SUM(NUM_HORAS) AS TOTAL_HORAS,
       MIN(FECHA_INICIO) AS FECHA_MAS_ANTIGUA,
       COUNT(datediff((FECHA_INICIO),(CURRENT_DATE))) AS dIAS_TRABAJADOS
	FROM EMPLEADOS_PROYECTOS
    WHERE PROYECTO
	GROUP BY PROYECTO
    ORDER BY COUNT(*) DESC;
        
        
     /*** MODIFICAR INFORME ANTERIOR, SÓLO PARA LOS PROYECTOS
          CON MÁS DE 3 EMPLEADOS
          TRABAJANDO**/
		
SELECT PROYECTO AS ID_PROYECTO,
       COUNT(*) AS CANTIDAD_EMPLEADOS_EN_PROYECTO,
	   SUM(NUM_HORAS) AS TOTAL_HORAS,
       MIN(FECHA_INICIO) AS FECHA_MAS_ANTIGUA,
       COUNT(datediff((FECHA_INICIO),(CURRENT_DATE))) AS dIAS_TRABAJADOS
	FROM EMPLEADOS_PROYECTOS
    WHERE PROYECTO
	GROUP BY PROYECTO
    HAVING COUNT(*)>3
    ORDER BY COUNT(*) DESC;
          
 /***PARA CADA DEPARTAMENTO, CANTIDAD DE PROYECTOS LANZADOS, Y TOTAL PRESUPUESTO
      INVERTIDO EN LOS DITINTOS PROYECTOS.
      ***/
        
SELECT DEPARTAMENTO AS DEPARTAMENTO,
       COUNT(*) AS CANTIDAD_PROYECTOS,
       SUM(PRESUPUESTO) AS TOTAL_PRESUPUESTO
	FROM PROYECTOS
    GROUP BY DEPARTAMENTO;
        
        