
/********* Combinación inner join de tablas
                    combinación interna ******************************************

/**  1 PARA CADA EMPLEADO DE LA EMPRESA
  SU CLAVE, SU NOMBRE Y SALARIO Y
    EL NOMBRE DEL DEPARTAMENTO
    AL QUE PERTENECE**/
    
    /***** LOS DATOS QUE ME PIDEN NO ESTÁN EN LA MISMA TABLA
        ESTÁN EN DOS TABLAS DISTINTAS
        
      SU CLAVE, SU NOMBRE Y SALARIO  ESTÁN  EN EMPLEADOS
      EL NOMBRE DEL DEPARTAMENTO ESTÁ EN LA TABLA DEPARTAMENTOS
      ***/
      
      /*** NECESITO MÁS DE UNA TABLA
           DOS TABLAS**/
           
      SELECT  E.ID_EMPLEADO AS CLAVE_EMPLEADO,
              E.NOMBRE AS EMPLEADO,
              E.SALARIO AS SALARIO,
              D.NOMBRE AS SU_DEPARTAMENTO
              
         FROM EMPLEADOS AS E INNER JOIN DEPARTAMENTOS AS D
                               ON E.DEPARTAMENTO=D.NUMERO;
      
      
     
                                /** REL E (1,1)**/
             /**** A CADA TUPLA DE E LE CORRESPONDE UNA TUPLA DE TABLA D**/                   
             /** TODOS LOS EMPLEADOS TIENEN UNA TUPLA EN D PARA COMBINAR - PEGAR**/                   
      
      
      /***2   POR CADA EMPLEADO  QUE ESTÁ SUPERVISADO
              OBTENER SU CLAVE Y SU NOMBRE
              Y EL NOMBRE DE SU SUPERVISOR**/
              
              SELECT  E.ID_EMPLEADO AS CLAVE_SUPERVISADO,
                      E.NOMBRE AS SUPERVISADO,
                      E.SUPERVISOR AS CLAVE_SUPERVISOR, /*ES.ID_EMPLEADO*/
                      ES.NOMBRE AS SUPERVISOR
                FROM EMPLEADOS AS E INNER JOIN EMPLEADOS AS ES
                                     ON E.SUPERVISOR=ES.ID_EMPLEADO; /*(0,1)*/
              
     
	 
	 
      /*** NO TODOS LOS EMPLEADOS TIENEN TUPLA PARA PEGAR,
           LOS QUE TIENEN SUPERVISOR = NULL NO ENCUENTRAN TUPLA EN EL LADO
                DERECHO---> 
                DESAPARECEN DE LA CONSULTA
                E SON 20 TUPLAS, SÓLO 11 ENCUENTRAN TUPLA PARA COMBINAR
                11 ESTÁN SUPERVISADOS***/
  /** PEGAR A CADA EMPLEADO LA TUPLA DE SU SUPERVISOR**/    
      
      
                                    /*REL E (0,1)*/                           
       /** ESTE INNER ME SIRVE PARA SELECCIONAR A LOS SUPERVISADOS**/                             
   
   /***                       
         3 PARA CADA EMPLEADO QUE ESTÉ SUPERVISADO
         OBTENER SU NOMBRE Y SALARIO Y EL NOMBRE DE SU DEPARTAMENTO**/
     
       
	 
     SELECT   E.NOMBRE  AS EMPLEADO_SUPERVISADO,
              E.SALARIO AS SU_SALARIO ,
              E.DEPARTAMENTO AS CLAVE_SU_DEPARTAMENTO,
              D.NOMBRE AS SU_DEPARTAMENTO
              
          FROM EMPLEADOS AS E INNER JOIN DEPARTAMENTOS AS D
                                ON E.DEPARTAMENTO=D.NUMERO  /*(1,1)*/
          WHERE E.SUPERVISOR IS NOT NULL; /* WHERE SUPERVISOR*/
	 
	 
   SELECT  E.NOMBRE AS SUPERVISADO,
           E.SALARIO AS SU_SALARIO,
           D.NOMBRE AS SU_DEPARTAMENTO
     FROM EMPLEADOS AS E INNER JOIN EMPLEADOS AS ES
                           ON E.SUPERVISOR=ES.ID_EMPLEADO /*(0,1)*/
                              INNER JOIN DEPARTAMENTOS AS D
                                 ON E.DEPARTAMENTO=D.NUMERO; /*(1,1)*/
                               
   
  /* CON EL PRIMER INNER JOIN HE SELECCIONADO A LOS SUPERVISADOS
      Y LUEGO SÓLO A ESTOS LE PEGO SU DEPARTAMENTO
      AUNQUE NO SE PIDE INFORMACIÓN DEL SUPERVISOR, 
      HEMOS COMBINADO A SU SUPERVISOR PARA 
      SELECCIONAR TUPLAS*/
  
 /**  4 PARA CADA EMPLEADO QUE ESTÉ SUPERVISADO, 
      SU NOMBRE, EL NOMBRE DE SU SUPERVISOR
      EL NOMBRE DE SU DIRECTOR**/
      
      SELECT   E.NOMBRE AS EMPLEADO_SUPERVISADO,
               ES.NOMBRE AS SU_SUPERVISOR,
               ED.NOMBRE AS SU_DIRECTOR
               
          FROM EMPLEADOS AS E INNER JOIN EMPLEADOS AS ES
                               ON E.SUPERVISOR=ES.ID_EMPLEADO /*(0,1)*/
                                  INNER JOIN DEPARTAMENTOS AS D
                                       ON E.DEPARTAMENTO=D.NUMERO /*(1,1)*/
                                          INNER JOIN EMPLEADOS AS ED   /*(1,1)*/
                                              ON D.DIRECTOR=ED.ID_EMPLEADO;
                                         
                                  
 /*EL ORDEN DE LAS TABLAS A COMBINAR ES IMPORTANTE XQ CON EL PRIMER INNER
    HAGO DOS COSAS SELECCIONO TUPLAS Y COMBINO**/
    


   /*** 5 PARA CADA DEPARTAMENTO DE LA EMPRESA,
      OBTENER UN INFORME CON:
      NOMBRE DEL DEPARTAMENTO,
      CANTIDAD DE EMPLEADOS ASIGNADOS A ÉL
      ******/
      
SELECT COUNT(E.ID_EMPLEADO) AS CANTIDAD_EMPLEADOS,
	   D.NOMBRE AS NOMBRE_DEPARTAMENTO
	FROM DEPARTAMENTOS AS D INNER JOIN EMPLEADOS AS E 
						  ON D.NUMERO=E.DEPARTAMENTO
	GROUP BY D.NUMERO;
      
   /** 6 AÑADE AL INFORME ANTERIOR EL NOMBRE Y SALARIO DE SU DIRECTOR Y 
       EL SALARIO MEDIO DEL DEPARTAMNETO (DE LOS EMPLEADOS ASIGNADOS AL DEPARTAMENTO)
       */                            
 
 SELECT COUNT(E.ID_EMPLEADO) AS CANTIDAD_EMPLEADOS,
	   D.NOMBRE AS NOMBRE_DEPARTAMENTO,
       AVG(E.SALARIO) AS SALARIO_MEDIO_DEPARTAMENTO,
       ED.NOMBRE AS NOMBRE_DIRECTOR
	FROM DEPARTAMENTOS AS D INNER JOIN EMPLEADOS AS E 
						  ON D.NUMERO=E.DEPARTAMENTO/*(1,1)*/
                            INNER JOIN EMPLEADOS AS ED
                              ON D.DIRECTOR=ED.ID_EMPLEADO/*(0,1)*/
	GROUP BY D.NUMERO;

   /*** PARA CADA DEPARTAMENTO  SU CLAVE,SU NOMBRE,
         NOMBRE Y SALARIO DE SU DIRECTOR**/
 SELECT D.NUMERO AS CLAVE_DEPARTAMENTO,
        D.NOMBRE AS NOMBRE_DEPARTAMENTO,
        ED.NOMBRE AS NOMBRE_DIRECTOR,
        ED.SALARIO AS SALARIO_DIRECTOR
	FROM DEPARTAMENTOS AS D INNER JOIN EMPLEADOS AS E
                              ON D.NUMERO=E.DEPARTAMENTO
                                INNER JOIN EMPLEADOS AS ED
                                  ON D.DIRECTOR=ED.ID_EMPLEADO
	GROUP BY D.NUMERO;
                           
                            /**REL D (1,1)**/       
                            
                            
	/*OBTENGA PARA CADA DEPARTAMENTO SU CLAVE Y NOMBRE Y NOMBRE  Y SALARIO DE SU DIRECTOR
    LA CANTIDAD DE EMPLEADOS ASIGNADOS AL DEPARTAMENTO LA CANTIDAD DE PROYECTOS QUE 
    TIENE LANZADOS
    */
    
    SELECT D.NUMERO AS CLAVE_DEPARTAMENTO,
		   D.NOMBRE AS NOMBRE_DEPARTAMENTO,
           ED.NOMBRE AS NOMBRE_DIRECTOR,
           ED.SALARIO AS SALARIO_DIRECTOR,
           COUNT(DISTINCT E.ID_EMPLEADO) AS CANTIDAD_EMPLEADOS,
           COUNT(DISTINCT -P.ID_PROYECTO) AS CANTIDAD_PROYECTOS
		FROM DEPARTAMENTOS AS D INNER JOIN EMPLEADOS AS ED
                                  ON D.DIRECTOR=ED.ID_EMPLEADO/*()1,1*/
                                     LEFT JOIN EMPLEADOS AS E
                                       ON D.NUMERO=E.DEPARTAMENTO /*(0,N)*/
                                         LEFT JOIN PROYECTOS AS P
											ON D.NUMERO=P.DEPARTAMENTO/*(0,N)*/
		GROUP BY D.NUMERO,D.NOMBRE;
 /*ejercicio  cuantos supervisores supervisan en cada deartamento del enunciado anterior*/    
 
     SELECT D.NUMERO AS CLAVE_DEPARTAMENTO,
		   D.NOMBRE AS NOMBRE_DEPARTAMENTO,
           ED.NOMBRE AS NOMBRE_DIRECTOR,
           ED.SALARIO AS SALARIO_DIRECTOR,
           COUNT(DISTINCT E.ID_EMPLEADO) AS CANTIDAD_EMPLEADOS,
           COUNT(DISTINCT -P.ID_PROYECTO) AS CANTIDAD_PROYECTOS,
           COUNT(DISTINCT ES.ID_EMPLEADO) AS CANTIDAD_SUPERVISORES
		FROM DEPARTAMENTOS AS D INNER JOIN EMPLEADOS AS ED
                                  ON D.DIRECTOR=ED.ID_EMPLEADO/*()1,1*/
                                     LEFT JOIN EMPLEADOS AS E
                                       ON D.NUMERO=E.DEPARTAMENTO /*(0,N)*/
                                         LEFT JOIN PROYECTOS AS P
											ON D.NUMERO=P.DEPARTAMENTO/*(0,N)*/
                                               LEFT JOIN EMPLEADOS AS ES
                                                 ON E.SUPERVISOR=ES.ID_EMPLEADO/*(0,N)*/
		GROUP BY D.NUMERO,D.NOMBRE;
 
 
 
 
 
 
/*TENGO INCORPORADA MAS DE UNA VEZ RELACION A MUCHOS */
                            
 /*** OBTENER POR CADA EMPLEADO QUE SEA DIRECTOR DE DEPARTAMENTO
      SU CLAVE, SU NOMBRE, NOMBRE DEL DEPARTAMENTO QUE DIRIGE,
      CANTIDAD DE EMPLEADOS A LOS QUE DIRIGE Y SALARIO MEDIO DE SUS EMPLEADOS
      **/
     
 /** PRIMER PASO:
     PEGAR A CADA EMPLEADO LA TUPLA DEL DEPARTAMENTO QUE DIRIGE
     ---->ESTO VA A SUPONER__> SELECCIONAR CON LOS DIRECTORES**/

                                          /*** (0,1)**/
    /**CON ESTE PRIMER PASO SELECCIONO A LOS EMPLEADOS QUE SON DIRECTORES**/                                      
  /** SEGUNDO PASO**/   
    /**D.DIRECTOR, D.NUMERO, E.DEPARTAMENTO**/
          
          
          
 /*** PARA CADA EMPLEADO
      SU NOMBRE Y SALARIO 
      Y LA CANTIDAD DE PROYECTOS EN LOS QUE ESTÁ TRABAJANDO
      FECHA DEL PRIMER DÍA DE TRABAJO ASIGNADO (DESDE QUÉ FECHA ESTÁ ASIGNADO A ALÚN PROYECTO)
      (SÓLO ME INTERESAN EN EL INFORME LOS EMPLEADOS QUE ESTÁN TRABAJANDO EN ALGÚN PROYECTO**/

    SELECT  E.NOMBRE AS NOMBRE_EMPLEADO,
            E.SALARIO AS SALARIO_EMPLEADO,
			EP.PROYECTO AS ID_PROYECTO,
			COUNT(*) AS CANTIDAD_PROYECTOS,
            MIN(EP.FECHA_INICIO) AS FECHA_INICIO
		FROM EMPLEADOS AS E INNER JOIN EMPLEADOS_PROYECTOS AS EP
                                ON E.ID_EMPLEADO=EP.EMPLEADO/*(0,N)*/
		GROUP BY E.ID_EMPLEADO;
        
/*CANTIDAD DE DIAS +*/
      
      /***UN EMPLEADO(UNA TUPLA DE TABLA EMPLEADOS 
            PARTICIPA (0,N) EN REL TRABAJAR EN PROYECTO
          LOS EMPLEADOS QUE NO TRABAJEN EN ALGÚN PROYECTO EN ESTE INSTANTE
          CON INNER JOIN DESAPARECEN DE LA CONSULTA**/
          
          
      
      
    /*CUÁNTOS TUPLAS HAY EN TABLA EMPLEADOS_PROYECTOS**/  
     
      
      /**CLAVES DE LOS EMPLEADOS QUE ESTÁN TRABAJANDO EN ALGÚN PROYECTO**/
      
     
      
      /** PARA CADA PROYECTO, QUE TENGA ALGÚN EMPLEADO TRABAJANDO,
          OBTENER:
          SU NOMBRE, SU PRESUPUESTO, EL NOMBRE DEL DEPARTAMENTO QUE LO LANZA,
          LA CANTIDAD DE EMPLEADOS QUE TRABAJAN EN EL PROYECTO 
          TOTAL HORAS DE TRABAJO EMPLEADAS EN EL PROYECTO
      *****/    
          
      /*** PRIMERO COMBINAMOS CADA TUPLA DE PROYECTO CON LA TUPLA DEL 
      DEPARTAMENTO QUE LO LANZA, PARTICIPACIÓN DE PROYECTO
      ES (1,1), NO PIERDO NINGÚN PROYECTO XQ TODOS COMBINAN UNA VEZ
      LUEGO A CADA PROYECTO LO COMBINAMOS CON LAS TUPLAS DE TABLA
      EMPLEADOS_PROYECTOS , LA PARTICIPACIÓN DE PROYECTO ES (0,N)
      , ENTONCES PUEDO PERDER PROYECTOS DE LA CONSULTA, TODOS LOS QUE NO ESTÉN EN
      ESTE INSTANTE REFERENCIADOS EN LA TABLA EMPLEADOS_PROYECTOS,
      Y OTROS PROYECTOS SE CLONAN N VECES__> NECESITO AGRUPAR
      ******************/
          
          
       /*** POR CADA  EMPLEADOS SUPERVISADO EN LA EMPRESA
            OBTENER:
            SU NOMBRE Y SALARIO,
            EL NOMBRE Y SALARIO  DE SU SUPERVISOR,
            EL NOMBRE DEL DEPARTAMENTO AL QUE PERTENECE
            EL NOMBRE Y SALARIO DE SU DIRECTOR **/
            
            
       /**** NO HAY QUE AGRUPAR TODAS LAS RELACIONES QUE USO EN LA CONSULTA
       SON CON PATICIPACIÓN MÁXIMO 1***/     
            
      
            
            
    /** SI NO ME PIDEN DATOS DE SU SUPERVISOR, CÓMO LA HACES ???**/       
    /*** POR CADA  EMPLEADOS SUPERVISADO EN LA EMPRESA
            OBTENER:
            SU NOMBRE Y SALARIO,
            EL NOMBRE DEL DEPARTAMENTO AL QUE PERTENECE
            EL NOMBRE Y SALARIO DE SU DIRECTOR **/        
            
            
    