/**********************************************************************************************************************************************
       ENUNCIADO:      CONTINÚA  ESTE  SCRIPT PARA OBTENER LA BASE DE DATOS BBDD_CURSOS_INTERNET_VER 3 
*************************************************************************************************************************************************
 SCRIPT DE CREACIÓN DE LA BASE DE DATOS
                                  BBDD_CURSOS_INTERNET_VER 3
                                        ESPECIALIZACIÓN DE LA ENTIDAD PROFESOR                                                             *****************/
                                  
                                  
  DROP DATABASE IF EXISTS BBDD_CURSOS_INTERNET_V3;
  
  CREATE DATABASE IF NOT EXISTS  BBDD_CURSOS_INTERNET_V3;
  
  USE BBDD_CURSOS_INTERNET_V3;
  
  
  
  /*****************************  TABLA AULAS PARA GUARDAR ENTIDAD AULA  Y TABLA TELEFONOS_AULAS PARA SU ATRIBUTO
                                                  MULTIVALUADO****************************/
  DROP TABLE IF  EXISTS AULAS;
  CREATE TABLE IF NOT EXISTS AULAS (
    ID_AULA INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOMBRE ENUM('SÓCRATES', 'ARISTÓTELES', 'PITÁGORAS', 'SÓFOCLES', 'PLATÓN') NOT NULL,
    LOCALIDAD VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(45) NULL,
    PRIMARY KEY (ID_AULA),
    UNIQUE INDEX U_NOM_LOC (NOMBRE , LOCALIDAD)
    
)  ENGINE INNODB;
  
  DROP TABLE IF EXISTS TELEFONOS_AULAS;
  CREATE TABLE IF NOT EXISTS TELEFONOS_AULAS
  ( 
       AULA  INT  UNSIGNED  NOT NULL,
       TELEFONO VARCHAR(10) NOT NULL,
       PRIMARY KEY (AULA, TELEFONO),
       FOREIGN KEY (AULA) REFERENCES AULAS(ID_AULA)
              ON DELETE CASCADE /* siempre*/
              ON UPDATE CASCADE,
       INDEX FK_AULA_TLF (AULA)       
              
  
  
  
  )ENGINE INNODB;

 
 /************  TABLA ALUMNOS    PARA GUARDAR ENTIDAD ALUMNO
                                                              ********************/
                                                              
  DROP TABLE IF EXISTS  ALUMNOS;
  CREATE TABLE IF NOT EXISTS ALUMNOS
  (
      DNI CHAR(9) NOT NULL,
      NOMBRE VARCHAR (50) NOT NULL,
      DIRECCION VARCHAR(60) NOT NULL,
      FECHA_NAC  DATE NOT NULL,
      TELEFONO  VARCHAR (10) NULL,
      E_MAIL     VARCHAR(45) NOT NULL,
      FOTO       BLOB NULL,
      DNI_DIG   BLOB NULL,
      AULA_ASIGNADA     INT  UNSIGNED NOT NULL,
	  FOREIGN KEY (AULA_ASIGNADA) REFERENCES AULAS(ID_AULA)
              ON DELETE RESTRICT
              ON UPDATE CASCADE,
       INDEX FK_AULA_ASIGNADA(AULA_ASIGNADA),
      PRIMARY KEY (DNI),
      /** RESTRICCIÓN DE UNICIDAD PARA COLUMNA E_MAIL, NOS SERVIRÁ DE CLAVE ALTERNATIVA**/
      UNIQUE INDEX AK_E_MAIL_ALUMNO (E_MAIL)
       
  
  ) ENGINE INNODB;
  
  
   /******************************* TABLA   PROFESORES PARA GUARDAR ENTIDAD PROFESOR***********/
  
  /** EN ESTA TABLA TENGO LA SUPERCLASE, ALMACENADOS A TODOS LOS PROFESORES
  ***/
  DROP TABLE IF EXISTS PROFESORES;
  CREATE TABLE IF NOT EXISTS PROFESORES
  (
      DNI  CHAR(9) NOT NULL,
      NOMBRE VARCHAR(50) NOT NULL,
      FECHA_NAC DATE NOT NULL,
      E_MAIL VARCHAR (45) NOT NULL,
      FECHA_ALTA  DATE NOT NULL,
      SALARIO  FLOAT NOT NULL DEFAULT 1500.0,
      SUPERVISOR CHAR(9) NULL,
    INDEX FK_SUPERVISOR(SUPERVISOR),
    DEPARTAMENTO INT UNSIGNED NOT NULL, 
    INDEX FK_DEPARTAMENTO_ASIGNADO(DEPARTAMENTO),
      PRIMARY KEY (DNI),
      UNIQUE INDEX AK_E_MAIL_PROF (E_MAIL)
       
  
  ) ENGINE INNODB;
  
   INSERT INTO `PROFESORES`
  (`DNI`, `NOMBRE`, `FECHA_NAC`, `E_MAIL`, `FECHA_ALTA`, `SALARIO`, `DEPARTAMENTO`) 
VALUES 
('36000001A', 'FERNANDO PEREZ PÉREZ ', '1988-12-02', 'ferpp@gmail.com', '2000-01-01', '1600', '1');

INSERT INTO `PROFESORES` 
(`DNI`, `NOMBRE`, `FECHA_NAC`, `E_MAIL`, `FECHA_ALTA`, `SALARIO`, `DEPARTAMENTO`) 
VALUES 
('36000002B', 'FRANCISCO LÓPEZ MIRA', '1990-01-23', 'fralm@gmail.com', '2000-02-01', '1600', '2');
INSERT INTO `PROFESORES`
 (`DNI`, `NOMBRE`, `FECHA_NAC`, `E_MAIL`, `FECHA_ALTA`, `SALARIO`, `DEPARTAMENTO`) 
 VALUES ('36000003C', 'PALOMA GARCÍA ACUÑA', '1988-11-26', 'palomagarciaacuña@gmail.com', '2001-01-01', '1700', '3');
 
INSERT INTO `PROFESORES`
 (`DNI`, `NOMBRE`, `FECHA_NAC`, `E_MAIL`, `FECHA_ALTA`, `SALARIO`, `DEPARTAMENTO`) 
 VALUES
 ('37000123G', 'SOLEDAD FERNÁNDEZ PÉREZ', '1991-02-03', 'soleadfp@gmail.com', '2000-03-04', '1600', '4');
  
  /*** UNA TABLA PARA LA SUBCLASE SUPERVISOR, CON DELETE EN CASCADE SIEMPRE**/
  DROP TABLE IF EXISTS SUPERVISORES;
  CREATE TABLE IF NOT EXISTS SUPERVISORES
  (
     DNI  CHAR(9) NOT NULL,
     PRIMARY KEY (DNI),
     FOREIGN KEY (DNI) REFERENCES PROFESORES(DNI)
           ON DELETE CASCADE /*SIEMPRE , DEP EN EXISTENCIA, ES EL MISMO*/
           ON UPDATE CASCADE
     /** ES LA ÚNICA VEZ QUE NO HAGO ÍNDICE PARA LA FK, PORQUE YA LO TENGO EN PRIMARY KEY*/
    
           
  
  )ENGINE INNODB;
  
  ALTER TABLE PROFESORES
     ADD FOREIGN KEY (SUPERVISOR) REFERENCES SUPERVISORES(DNI)
            ON DELETE SET NULL  /** FIJARSE**/
             ON UPDATE CASCADE;
  
  /*** UNA TABLA PARA LA SUBCLASE DIRECTOR, CON DELETE EN CASCADE SIEMPRE**/
  
  DROP TABLE IF EXISTS DIRECTORES;
  CREATE TABLE IF NOT EXISTS DIRECTORES
  (
     DNI  CHAR(9) NOT NULL,
     PRIMARY KEY (DNI),
     /***********
        DEPARTAMENTO INTEGER UNDIGNED NOT NULL,
     /************************************************/
     FOREIGN KEY (DNI) REFERENCES PROFESORES(DNI)
           ON DELETE CASCADE /*SIEMPRE , DEP EN EXISTENCIA, ES EL MISMO*/
           ON UPDATE CASCADE
     /** ES LA ÚNICA VEZ QUE NO HAGO ÍNDICE PARA LA FK, PORQUE YA LO TENGO EN PRIMARY KEY*/
   /***** 
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTOS (ID_DEPARTAMENTO)
              ON DELETE CASCADE
              ON UPDATE CASCADE
    UNIQUE INDEX FK_DEPARTAMENTO(DEPARTAMENTO)
    **************/
  
  )ENGINE INNODB;
    INSERT INTO DIRECTORES
       SELECT DNI FROM PROFESORES;
       
  /*UNA TABLA PARA LA LISTA DE ADMINISTRADORES ***/
  
  DROP TABLE IF EXISTS ADMINISTRADORES;
  CREATE TABLE IF NOT EXISTS ADMINISTRADORES (
    DNI CHAR(9) NOT NULL,
    PRIMARY KEY (DNI),
    FOREIGN KEY (DNI)
        REFERENCES PROFESORES (DNI)
        ON DELETE CASCADE ON UPDATE CASCADE,
	AULA INT  UNSIGNED NOT NULL,   /** ADMINISTRADOR PARTICIPA CON OBLIGATORIEDAD  (1,1)*/
	DIA_SEMANA  SET ('LUNES','MARTES','JUEVES') NOT NULL,
	PRECIO_HORA  FLOAT NOT NULL DEFAULT 120.5,
	NUM_HORAS_SEM INTEGER NOT NULL DEFAULT 5,
            
      FOREIGN KEY (AULA) REFERENCES AULAS (ID_AULA)
             ON DELETE CASCADE  /**FIJARSE**/
             ON UPDATE CASCADE,
      INDEX FK_AULA_ADMINISTRADA (AULA)  
)  ENGINE INNODB;
  
  /** UNA TABLA PARA LA ESPECIALIZACIÓN EVALUADORES***/
  
   DROP TABLE IF EXISTS EVALUADORES;
  CREATE TABLE IF NOT EXISTS EVALUADORES
  (
     DNI  CHAR(9) NOT NULL,
     PRIMARY KEY (DNI),
     FOREIGN KEY (DNI) REFERENCES PROFESORES(DNI)
           ON DELETE CASCADE /*SIEMPRE , DEP EN EXISTENCIA, ES EL MISMO*/
           ON UPDATE CASCADE
     /** ES LA ÚNICA VEZ QUE NO HAGO ÍNDICE PARA LA FK, PORQUE YA LO TENGO EN PRIMARY KEY*/
    
           
  
  )ENGINE INNODB;
  
  
  
    /*****************************  TABLA DEPARTAMENTOS PARA GUARDAR  ENTIDAD DEPARTAMENTO*******/
  
  DROP TABLE IF EXISTS DEPARTAMENTOS;
  CREATE TABLE IF NOT EXISTS DEPARTAMENTOS
  (
    ID_DEPARTAMENTO INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR (20)  NOT NULL,
    E_MAIL     VARCHAR(45) NOT NULL,
    DIRECTOR CHAR(9) NOT NULL,
    PRIMA_DIRECTOR FLOAT NOT NULL  DEFAULT 250.5 ,
    FECHA DATE NOT NULL,
    PRIMARY KEY(ID_DEPARTAMENTO),
    
    UNIQUE INDEX AK_E_MAIL_DEP (E_MAIL),
    FOREIGN KEY (DIRECTOR) REFERENCES DIRECTORES(DNI) 
                             ON DELETE RESTRICT
                             ON UPDATE CASCADE,
    UNIQUE INDEX FK_DIRECTOR(DIRECTOR)                           
  
    
  
  ) ENGINE INNODB;
  
  
   INSERT INTO DEPARTAMENTOS 
    (`NOMBRE`, `E_MAIL`, `DIRECTOR`, `FECHA`) 
    VALUES 
   ('MATEMÁTICAS', 'empresa.matem@gmail.com', '36000001A', '2000-01-01'),
   ('INFORMÁTICA', 'empresa.inform.@gmail.com', '36000002B', '2001-12-14'),
   ('FILOSOFÍA', 'empresa.filosofia@gmail.com', '36000003C', '2000-03-12'),
   ('IDIOMAS', 'empresa.idiomas@gmail.com', '37000123G', '2001-02-20');
  
   ALTER TABLE PROFESORES
      ADD FOREIGN KEY(DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO)
           ON DELETE RESTRICT /** FIJARSE**/
           ON UPDATE CASCADE;
  
  
  
  /*******************************TABLA  CURSOS   PARA GUARDAR ENTIDAD CURSO ************************************************/
  DROP TABLE IF EXISTS CURSOS;
  CREATE TABLE IF NOT EXISTS CURSOS
  (
    ID_CURSO INT UNSIGNED  AUTO_INCREMENT NOT NULL,
    NOMBRE  VARCHAR(30) NOT NULL,
    DURACION   INT NOT NULL DEFAULT 300 ,
    PRECIO      FLOAT NOT NULL DEFAULT 650.0,
    URL_CURSO VARCHAR(100) NOT NULL,
    LIBRO  VARCHAR(60)  NULL,
    DELEGADO CHAR(9) NOT NULL,
    FOREIGN KEY (DELEGADO) REFERENCES ALUMNOS(DNI) 
                             ON DELETE RESTRICT
                             ON UPDATE CASCADE,
    INDEX FK_DELEGADO(DELEGADO), 
    EVALUADOR CHAR(9) NOT NULL,
    FECHA_EVALUADOR DATE NOT NULL,
    HORA_EVALUADOR   INT NOT NULL,
    INDEX FK_EVALUADOR(EVALUADOR), 
    PRIMARY KEY (ID_CURSO),
    UNIQUE INDEX AK_NOMBRE_CURSO (NOMBRE),
    UNIQUE INDEX AK_URL_CURSO(URL_CURSO)
  
  
  
  )ENGINE INNODB;
  
  
    /**************************  TABLA PARA RELACIÓN (N:M) PROFESOR IMPARTE CURSO***/
  
  DROP TABLE IF EXISTS PROFESORES_CURSOS;
  
  CREATE TABLE IF NOT EXISTS PROFESORES_CURSOS
  (
        PROFESOR  CHAR(9) NOT NULL,
        CURSO   INT UNSIGNED  NOT NULL,
        NUM_HORAS INT NOT NULL DEFAULT 7,
        PRECIO_HORA FLOAT NOT NULL  DEFAULT 120.0,
        
        PRIMARY KEY(PROFESOR, CURSO),
        FOREIGN KEY(PROFESOR) REFERENCES PROFESORES(DNI)
                             ON DELETE CASCADE
                             ON UPDATE CASCADE,
         INDEX FK_PROFEOSR_IMPARTE (PROFESOR),
         FOREIGN KEY (CURSO) REFERENCES CURSOS(ID_CURSO)
                             ON DELETE CASCADE
                             ON UPDATE CASCADE,
          INDEX FK_CURSO_IMPARTIDO (CURSO)                   
  
    
  ) ENGINE INNODB;
  
  
   /**************************  TABLA PARA RELACIÓN (N:M) ALUMNO MATRICULADO EN  CURSO***/
  DROP TABLE IF EXISTS ALUMNOS_CURSOS;
  
  CREATE TABLE IF NOT EXISTS ALUMNOS_CURSOS
  (
     ALUMNO CHAR(9) NOT NULL,
     CURSO   INT UNSIGNED  NOT NULL,
     FECHA_MATRICULA DATE NOT NULL,
     NOTA   ENUM ('APTO', 'NO APTO', 'SIN EVALUAR')  NOT NULL  DEFAULT 'SIN EVALUAR',
     PRIMARY KEY (ALUMNO, CURSO),
     FOREIGN KEY (ALUMNO) REFERENCES ALUMNOS(DNI)
                          ON DELETE CASCADE
                          ON UPDATE CASCADE,
     INDEX FK_ALUMNO_MATRICULADO(ALUMNO),                     
     FOREIGN KEY (CURSO) REFERENCES CURSOS(ID_CURSO)
                             ON DELETE RESTRICT
                             ON UPDATE CASCADE,
     INDEX FK_CURSO_IMPARTIDO (CURSO) 
  
  
  ) ENGINE INNODB;
 
 