/*   ordenes para crear la base de datos 
    instituto */
    
    
    CREATE DATABASE IF NOT EXISTS INSTITUTO;
    
    USE INSTITUTO;
    
    CREATE TABLE IF NOT EXISTS ALUMNOS
    (
      ID_ALUMNO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
      NOMBRE  VARCHAR(35) NOT NULL,
      FECHA_NAC DATE NOT NULL,
      PESO FLOAT NULL,
      /*COLUMNAS PARA LA RELACIÓN ALUMNO ESTÁ MATRIULADO
          EN UN CURSO**/
      CURSO INTEGER UNSIGNED  NOT NULL,
      FOREIGN KEY (CURSO) REFERENCES CURSOS(ID_CURSO)
                       ON DELETE CASCADE 
                       ON UPDATE CASCADE,
      FECHA_MAT DATE NOT NULL,
      HORA_MAT TIME NOT NULL,
      PRIMARY KEY(ID_ALUMNO),
      
      INDEX FK_CURSO_MATRICULADO (CURSO) 
          /**RELACIÓN (1:N) EL ÍNDICE ES INDEX*/
      
      
    );
    
    CREATE TABLE IF NOT EXISTS CURSOS
    (
       ID_CURSO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
       NOMBRE VARCHAR(30) NOT NULL,
       TURNO ENUM('ORDINARIO','ADULTOS') NOT NULL,
       NIVEL ENUM('MEDIO','SUPERIOR'),
       DELEGADO INTEGER UNSIGNED NOT NULL,
              /* NOT NULL PORQUE CURSO PARTICIPA (1,1)*/
       PRIMARY KEY (ID_CURSO),
       FOREIGN KEY (DELEGADO) REFERENCES ALUMNOS(ID_ALUMNO)
                              ON DELETE RESTRICT
                              ON UPDATE CASCADE,
       UNIQUE INDEX  AK_CURSOS (NOMBRE),                       
       UNIQUE INDEX  FK_DELEGADO_U (DELEGADO)                       
    );           /*RELACIÓN (1:1) EL ÍNDICE ES UNIQUE INDEX**/
    
    ALTER TABLE ALUMNOS
     ADD
      FOREIGN KEY (CURSO) REFERENCES CURSOS(ID_CURSO)
                     ON DELETE RESTRICT
                     ON UPDATE CASCADE;
    
    
    CREATE TABLE IF NOT EXISTS MODULOS
    (
       CODIGO CHAR(5) NOT NULL,
       NOMBRE VARCHAR(30) NOT NULL,
       HORAS_SEMANALES INTEGER NOT NULL,
       DURACION INTEGER NOT NULL,
       CURSO INTEGER UNSIGNED NOT NULL,
       PRIMARY KEY (CODIGO),
       FOREIGN KEY (CURSO) REFERENCES CURSOS(ID_CURSO)
                       ON DELETE CASCADE /*DEPENDE EN EXISTENCIA*/
                       ON UPDATE CASCADE,
       INDEX FK_MODULO_DE_CURSO (CURSO) 
           /**RELACIÓN (1:N) EL ÍNDICE ES INDEX*/
    );
    
    