/**  ENUNCIADO  1: Jesús Blanco Miguez
         PARA AQUELLOS DEPARTAMENTOS QUE TENGAN  ALGÚN PROYECTO LANZADO
         OBTENER 
         SU NOMBRE,
         CLAVE DE SU DIRECTOR
         CANTIDAD DE EMPLEADOS QUE ESTÁN ASIGNADOS AL DEPARTAMENTO 
         SU SALARIO MEDIO         
      **/
      
      /*** SE PUEDE HACER DE DOS FORMAS, LA SELECCIÓN DE LOS DEPARTAMENTOS
           A) COMBINACIÓN INTERNA ENTRE DEPARTAMENTOS Y PROYECTOS
           B) MEDIANTE UNA SUBCONSULTA
       ******/

SELECT D.NOMBRE AS DEPARTAMENTO,
	   D.DIRECTOR AS CLAVE_DIRECTOR,
       COUNT(DISTINCT E.ID_EMPLEADO) AS CANTIDAD_EMPLEADOS,
       AVG(SALARIO) AS SALARIO_MEDIO
	FROM DEPARTAMENTOS AS D INNER JOIN PROYECTOS AS P /*(1,N)*/
                               ON P.DEPARTAMENTO=D.NUMERO
                                 LEFT JOIN EMPLEADOS AS E /*(0,N)*/
                                     ON D.NUMERO=E.DEPARTAMENTO
	GROUP BY D.NUMERO;
    
SELECT D.NOMBRE AS DEPARTAMENTO,
	   D.DIRECTOR AS CLAVE_DIRECTOR,
       (SELECT COUNT(E.ID_EMPLEADO) 
		FROM EMPLEADOS AS E
        WHERE E.DEPARTAMENTO=D.NUMERO
       )AS CANTIDAD_EMPLEADOS,
       (SELECT AVG(SALARIO) 
		FROM EMPLEADOS AS E
        WHERE E.DEPARTAMENTO=D.NUMERO 
        )AS SALARIO_MEDIO
	FROM DEPARTAMENTOS AS D 
    WHERE D.NUMERO IN (
						SELECT DISTINCT DEPARTAMENTO
                        FROM PROYECTOS
                      );
	      
	   /** ENUNCIADO 2:	   
	       OBTENER PARA AQUELLOS PROYECTOS QUE TENGAN MÁS DE DOS EMPLEADOS TRABAJANDO EN ÉL
           CLAVE DE PROYECTO, CANTIDAD DE EMPLEADOS TRABAJANDO, Y TOTAL DE HORAS DE TRABAJO EN EL PROYECTO
*****************/		

SELECT	EP.PROYECTO AS CLAVE_PROYECTO,
		COUNT(*) AS CANTIDAD_EMPLEADOS,
        SUM(NUM_HORAS) AS TOTAL_HORAS
	FROM EMPLEADOS_PROYECTOS AS EP
    GROUP BY EP.PROYECTO
	HAVING COUNT(*)>2;

/** ENUNCIADO 3:
               AÑADIR AL INFORME ANTERIOR,
			   LA CANTIDAD DE EMPLEADOS DIRECTORES QUE TRABAJAN EN EL PROYECTO
			   ***/

SELECT	EP.PROYECTO AS CLAVE_PROYECTO,
		COUNT(*) AS CANTIDAD_EMPLEADOS,
        SUM(NUM_HORAS) AS TOTAL_HORAS,
        (SELECT COUNT(DIRECTOR)
			FROM DEPARTAMENTOS AS D
            WHERE EP.EMPLEADO=D.DIRECTOR
		)AS CANTIDAD_DIRECTORES
	FROM EMPLEADOS_PROYECTOS AS EP
    GROUP BY EP.PROYECTO
	HAVING COUNT(*)>2;
			   
 	    /** 
           ENUNCIADO 4:
           PARA CADA SUPERVISOR
           SU CLAVE Y CANTIDAD DE PROYECTOS EN LOS QUE TRABAJA Y TOTAL HORAS
           DE TRABAJO EN LOS DISTINTOS PROYECTOS
           INTERESAN TODOS LOS SUPERVISORES 
           CANTIDAD DE SUPERVISADOS QUE ATIENDE
           Y SALARIO MEDIO DE SUS SUPERVISADOS
        *******/  
        
SELECT  E.SUPERVISOR AS CLAVE_SUPERVISOR,
        COUNT(EP.PROYECTO) AS CANTIDAD_PROYECTOS,
        SUM(EP.NUM_HORAS) AS TOTAL_HORAS,
        COUNT(E.ID_EMPLEADO) AS CANTIDAD_SUPERVISADOS,
        AVG(E.SALARIO) AS SALARIO_MEDIO
	FROM EMPLEADOS AS E LEFT JOIN EMPLEADOS_PROYECTOS AS EP /*0,N*/
                          ON E.ID_EMPLEADO=EP.EMPLEADO
    WHERE SUPERVISOR
    GROUP BY E.SUPERVISOR;