/*Jesus Blanco Miguez 1º Dam*/

/**   PARA CADA PROYECTO QUE ESTÉ CON TRABAJO INICIADO, OBTENER:
     SU CLAVE, LA CANTIDAD DE EMPLEADOS TRABAJANDO EN ÉL, TOTAL HORAS DE TRABAJO,
     LA CANTIDAD DE EMPLEADOS SUPERVISADOS TRABAJANDO EN ÉL**/
     
	SELECT 	P.ID_PROYECTO AS CLAVE,
			COUNT(EP.EMPLEADO) AS CANTIDAD_EMPLEADOS,
			SUM(EP.NUM_HORAS) AS TOTAL_HORAS,
			COUNT(E.SUPERVISOR IS NOT NULL) AS CANTIDAD_EMPLEADOS_SUPERVISADOS
		
		FROM PROYECTOS AS P LEFT JOIN EMPLEADOS_PROYECTOS AS EP
									ON EP.PROYECTO=P.ID_PROYECTO
										LEFT JOIN EMPLEADOS AS E
											ON EP.EMPLEADO=E.ID_EMPLEADO
		GROUP BY P.ID_PROYECTO;
   
   
   /*** MODIFICA LA CONSULTA ANTERIOR:
          PARA CADA PROYECTO QUE ESTÉ CON TRABAJO INICIADO, Y TENGA MÁS DE 3 EMPLEADOS TRABAJANDO
          OBTENER:
          SU CLAVE, LA CANTIDAD DE EMPLEADOS TRABAJANDO EN ÉL, TOTAL HORAS DE TRABAJO,
          LA CANTIDAD DE EMPLEADOS SUPERVISADOS TRABAJANDO EN ÉL**/
          
     SELECT	P.ID_PROYECTO AS CLAVE,
			COUNT(EP.EMPLEADO) AS CANTIDAD_EMPLEADOS,
			SUM(EP.NUM_HORAS) AS TOTAL_HORAS,
			COUNT(E.SUPERVISOR IS NOT NULL) AS CANTIDAD_SUPERVISADOS
		
		FROM PROYECTOS AS P LEFT JOIN EMPLEADOS_PROYECTOS AS EP
									ON EP.PROYECTO=P.ID_PROYECTO
										LEFT JOIN EMPLEADOS AS E
											ON EP.EMPLEADO=E.ID_EMPLEADO
		HAVING COUNT(EP.EMPLEADO)>3;     
          
          
          
     
/**PARA CADA POYECTO QUE ESTÉ CON TRABAJO INICIADO, OBTENER:
   SU CLAVE, NOMBRE DE PROYECTO Y PRESUPUESTO, CANTIDAD DE EMPLEADOS TRABAJANDO EN EL PROYECTO,
   CANTIDAD DE EMPLEADOS QUE PERTENEZCAN AL MISMO DEPARTAMENTO QUE EL PROYECTO TRABAJANDO EN ÉL
   
   *****/
   
SELECT	P.ID_PROYECTO AS CLAVE,
		P.NOMBRE AS NOMBRE,
		COUNT(EP.EMPLEADO) AS CANTIDAD_EMPLEADOS,
		COUNT(D.NUMERO) AS CANTIDAD_EMPLEADOS_DEPARTAMENTO
		
	FROM PROYECTOS AS P LEFT JOIN EMPLEADOS_PROYECTOS AS EP
								ON EP.PROYECTO=P.ID_PROYECTO
									LEFT JOIN DEPARTAMENTOS AS D
										ON P.DEPARTAMENTO=D.NUMERO
	GROUP BY P.ID_PROYECTO;   