/** RECORDAMOS PODEMOS CREAR ÍNDICES (ÚNICOS/NO ÚNICOS) PARCIALES
    CON PARTE DE LOS CARACTERES DE UNA COLUMNA, ESTO LO HACEMOS PARA ALIGERAR EL ÍNDICE*/
    use empresa;

DROP INDEX    BUSCA_NOMBRE_FAMILIAR ON FAMILIARES;

CREATE  UNIQUE  INDEX BUSCA_NOMBRE_FAMILIAR 
   ON FAMILIARES (NOMBRE(20));
/*** EL ÍNDICE 
     SE CREA 
     CON LOS 20 PRIMEROS 
     CARACTERES DE CADA NOMBRE**/
	 
	    
 /** ESTA MISMA ORDEN LA PODEMOS ESCRIBIR  DE ESTA OTRA FORMA :**/
 DROP INDEX    BUSCA_NOMBRE_FAMILIAR ON FAMILIARES;
 ALTER TABLE FAMILIARES
    ADD INDEX BUSCA_NOMBRE_FAMILIAR (NOMBRE (20) ); 
 

 
 /* RECORDAD TAMBIÉN PODEMOS DEFINIR ÍNDICES COMPUESTOS POR VARAS COLUMNAS (HASTA 16 COLUMNAS)
 **/
 
 CREATE INDEX BUSCA_DATOS ON FAMILIARES
    (PARENTESCO, FECHA_NAC );
	
	
  /** LA ORDEN SHOW INDEX  NOS PERMITE VER INFORMACIÓN SOBRE LOS ÍNDICES ASOCIADOS A UNA TABLA
      FIJARSE BIEN EN EL INFORME QUE NOS MUESTRA ESTA ORDEN
      Y OBTENER TODAD LA INFORMACIÓN POSIBLE*/
         
    SHOW INDEX FROM EMPLEADOS; 
	/* OTRAS SINTAXIS:  SHOW INDEXES FROM EMPLEADOS;  SHOW KEYS FROM EMPLEADOS;*/
	SHOW INDEXES FROM EMPLEADOS;
    SHOW KEYS FROM EMPLEADOS;
    
     /*la cardinalidad de un indece es el numero de elementos que tiene distintos*/
    
    /*PARA VER INFORME DE LOS ÍNDICES CREADOS EN LA TABLA FAMILIARES:
      FIJARSE COMO MUESTRA LOS ÍNDICES COMPUESTOS POR VARIAS COLUMNAS*/
      
      
    SHOW INDEX FROM FAMILIARES;
    
    
  /** IMAGINAR, POR EJEMPLO,QUE OBSERVAMOS QUE SE UTILIZA MUY FRECUENTEMENTE EL DATO
     FECHA_INICIO DE LA TABLA EMPLEAODS_PROYECTOS.*/
     
     /* PARA CADA DÍA , 
        DAME LA CANTIDAD DE EMPLEADOS QUE INICIARON
         EL TRABAJO ESE DÍA **/
         
         SELECT  EP.FECHA_INICIO AS DIA,
                 COUNT(*) AS CANTIDAD_DE_TRABAJO_INICIADO_ESE_DIA
            FROM EMPLEADOS_PROYECTOS AS EP
            GROUP BY EP.FECHA_INICIO;
         
         /** VERSIÓN B DE ESTA CONSULTA:
              (SÓLO QUEREMOS TENER EN CUENTA EN EL INFORME
		 LOS PROYECTOS LANZADOS POR EL DEPARTAMENTO DE VENTAS)
         ******/
         
         SELECT    EP.FECHA_INICIO AS FECHA,
                   COUNT(*) AS CANTIDAD_DE_TRABAJO_INICIADO_ESE_DIA 
             FROM EMPLEADOS_PROYECTOS AS EP
             WHERE PROYECTO IN (
                                    SELECT   ID_PROYECTO
                                       FROM PROYECTOS
                                       WHERE DEPARTAMENTO =(
                                                             SELECT NUMERO
                                                               FROM DEPARTAMENTOS
                                                               WHERE NOMBRE='VENTAS'                                                             
                                                           )
                               )
             GROUP BY  EP.FECHA_INICIO; 
			 /*
                      !!!!! ESTE GROUP BY 
                             GROUP BY EP.FECHA_INICIO
                             NO ENCUENTRA ÍNDICE, SE EJECUTA PERO.. MUY COSTOSO*/
         
         
     
  /** SI SUCEDE ESO, NOSOTROS PODEMOS PENSAR EN AGILIZAR LAS CONSULTAS 
      QUE FRECUENTEMENTE SE EJECUTAN USANDO EN WHERE, EN GROUP BY, EN ORDER BY, 
      LA COLUMNA FECHA_INICIO  QUE AHORA NO TIENE ASOCIADO UN ÍNDICE**/
      
      ALTER TABLE EMPLEADOS_PROYECTOS
          ADD INDEX BUSCA_FECHA (FECHA_INICIO  DESC);
		  
    /* ESTA VEZ AL CREAR EL ÍNDICE UTILIZO LA OPCIÓN DESC ( ORDENADO EL ÍNDICE DE MAYOR A MENOR)
       PORQUE PODEMOS SUPONER  QUE LAS FECHAS QUE MÁS VAMOS A CONSULTAR EN WHERE O EN ORDER BY DESC  SON LAS MAS CERCANAS AL DÍA DE HOY*/
	   
	/* LEE CON ATENCIÓN LA INFORMACIÓN QUE SUMINISTRA LA SIGUIENTE ORDEN*/
	
    SHOW INDEX FROM EMPLEADOS_PROYECTOS;
     
     
     /********************************************** SENTENCIA EXPLAIN********************************/
     
    /** OBSERVA ESTA CONSULTA, PONLE ENUNCIADO Y EJECÚTALA*/
	/*obten el total de salarios distintos que hay y cuantos empleados cobran el mismo salario*/
     SELECT    SALARIO, 
               COUNT(*) AS EMPLEADOS_CON_MISMO_SALARIO
         FROM EMPLEADOS
         GROUP BY SALARIO;
         
    /** AHORA VAMOS A ANALIZARLA CON  LA SENTENCIA EXPLAIN*/
	
     EXPLAIN   SELECT SALARIO, 
					  COUNT(*) AS EMPLEADOS_CON_MISMO_SALARIO
					FROM EMPLEADOS
					GROUP BY SALARIO;  
  /** EL GESTOR NO HA ENCONTRADO NINGÚN ÍNDICE PARA UTILIZAR EN LA EJECUCIÓN DE LA CONSULTA*/ 
  
  /** OBSERVA ESTA  OTRA CONSULTA, PONLE ENUNCIADO Y EJECÚTALA*/              
               
  SELECT   E.NOMBRE, E.SALARIO,
           D.NOMBRE, D.FECHA_INICIO
      FROM EMPLEADOS  AS E INNER JOIN DEPARTAMENTOS AS D
                           ON E.ID_EMPLEADO=D.DIRECTOR;
                           
    /** AHORA VAMOS A ANALIZARLA CON  LA SENTENCIA EXPLAIN*/  
	
   EXPLAIN SELECT   E.NOMBRE, E.SALARIO,
                    D.NOMBRE, D.FECHA_INICIO
           FROM EMPLEADOS  AS E INNER JOIN DEPARTAMENTOS AS D
                           ON E.ID_EMPLEADO=D.DIRECTOR;      
    

/* LA SENTENCIA EXPLAIN SE UTILIZA DELANTE DE UNA CONSULTA SELECT PARA ANALIZAR SU EJECUCIÓN,
   EXPLAIN DELANTE DE TABLA OBTIENE EL MISMO INFORME QUE DESCRIBE TABLA;  */	
   
   
    EXPLAIN  EMPLEADOS;  
    DESCRIBE EMPLEADOS;