/*FUNCIÓN QUE OBTENGA EL SALARIO MEDIO DE LOS SUPERVISORES
**/

/** DE DOS FORMAS, UNA DE ELLAS HACIENDO USO DE LA FUNCIÓN
    SI_SUPERVISOR*/
    
 DELIMITER $$
 USE EMPRESA $$
 
 DROP FUNCTION IF EXISTS SALARIO_MEDIO_SUPERVISORES $$
 CREATE FUNCTION SALARIO_MEDIO_SUPERVISORES (  )
 RETURNS DOUBLE
 READS SQL DATA
 BEGIN
     DECLARE SALARIO_MEDIO DOUBLE;
     SELECT   AVG(SALARIO) INTO SALARIO_MEDIO
         FROM EMPLEADOS
         WHERE ID_EMPLEADO IN (
                                 SELECT DISTINCT SUPERVISOR
                                     FROM EMPLEADOS 
                                     WHERE SUPERVISOR IS NOT NULL
         
                               ); 
     IF SALARIO_MEDIO IS NULL 
                   THEN RETURN 0;
                   ELSE RETURN SALARIO_MEDIO; 
     END IF;              
     
 
 END$$
    
 /** DE OTRA FORMA.....*/
 
 DROP FUNCTION IF EXISTS SALARIO_MEDIO_SUPERVISORES_VER2 $$
 CREATE FUNCTION SALARIO_MEDIO_SUPERVISORES_VER2 (  )
 RETURNS DOUBLE
 READS SQL DATA
 BEGIN
     DECLARE SALARIO_MEDIO DOUBLE;
     SELECT   AVG(SALARIO) INTO SALARIO_MEDIO
         FROM EMPLEADOS
         WHERE SI_SUPERVISOR(ID_EMPLEADO);
     IF SALARIO_MEDIO IS NULL 
                   THEN RETURN 0;
                   ELSE RETURN SALARIO_MEDIO; 
     END IF;              
   /* EN ESTE SEGUNDO FORMATO ESTOY HACIENDO USO, DENTRO DEL CUERPO DE LA FUNCIÓN, DE OTRA FUNCIÓN*/
   
   
 
 END$$
 /*ESTÁ SEGUNDA FUNCIÓN DEPENDE DE QUE EXISTA EN TODO MOMENTO,
       EL OBJETO FUNCTION SI_DIRECTOR**/   
/** SI ELIMINAMOS LA FUNCIÓN SI_SUPERVISOR DE NUESTRA BASE DE DATOS,
    AL LANZAR LA FUNCIÓN SALARIO_MEDIO_SUPERVISORES_VER2
    NOS DARÁ ESTE ERROR:
    Error Code: 1305. FUNCTION empresa.SI_SUPERVISOR does not exist
    **/
 
    
