/** Subir el sueldo un 2%
    a los directores, 
    que tengan en el daepartamento que dirigen más de 3 empleados**/
    
    
UPDATE     EMPLEADOS AS E INNER JOIN DEPARTAMENTOS AS D
                        ON E.ID_EMPLEADO=D.DIRECTOR
    SET E.SALARIO= E.SALARIO*1.02
    WHERE NUM_EMPLEADOS_DEP(D.NUMERO)>3;
       /*** EN WHERE USO LA FUNCIÓN**/
    
/**  CONSULTA:
     DIME POR CADA DEPARTAMENTO SU NOMBRE Y LA CANTIDAD DE EMPLEADOS QUE TIENE
    ASIGNADO**/
    
    
    /*** SI TENGO LA FUNCIÓN */
    
    SELECT   NOMBRE AS DEPARTAMENTO, 
             NUM_EMPLEADOS_DEP(NUMERO) AS CANTIDAD_EMPLEADOS
        FROM DEPARTAMENTOS;
    /*  AQUÍ HEMOS HECHO USO DE LA FUNCIÓN EN COLUMNA DE SELECCIÓN **/
    
    SELECT    NOMBRE AS DEPARTAMENTO,
              (
                   SELECT  COUNT(*)
                      FROM EMPLEADOS
                      WHERE DEPARTAMENTO=D.NUMERO
              
              ) AS CATIDAD_EMPLEADOS
    
        FROM DEPARTAMENTOS AS D;
        
/** AQUÍ HEMOS EMPLEADO UNA SUBCONSULTA CORRELACIONADA**/


SELECT   D.NOMBRE AS DEPARTAMENTO,
         COUNT(E.ID_EMPLEADO) AS CANTIDAD_EMPLEADOS
    FROM DEPARTAMENTOS AS D LEFT JOIN EMPLEADOS AS E
                              ON D.NUMERO=E.DEPARTAMENTO /*(0,N)*/
    GROUP BY D.NUMERO;    
/** AQUÍ HEMOS EMPLEADO UN COMBINACIÓN EXTRENA LEFT**/    
    
  SELECT   D.NOMBRE AS DEPARTAMENTO,
         COUNT(E.ID_EMPLEADO) AS CANTIDAD_EMPLEADOS
    FROM  EMPLEADOS AS E RIGHT JOIN DEPARTAMENTOS AS D
                              ON D.NUMERO=E.DEPARTAMENTO /*(0,N)*/
    GROUP BY D.NUMERO;    
/** AQUÍ HEMOS EMPLEADO UN COMBINACIÓN EXTRENA RIGHT, LA TABLA "IMPORTANTE"
     EN ESTA CONSULTA ESTÁ A LA DERECHA EN FROM**/   
     
     
     INSERT INTO DEPARTAMENTOS
     VALUES
     (NULL,'NUEVO DEPARTAMENTO',5,1200.0,'2023-04-27');
     
/* CONSULTO AHORA*/     
 SELECT NOMBRE, NUM_EMPLEADOS_DEP(NUMERO)
    FROM DEPARTAMENTOS
    WHERE NUMERO=5;   