 /** DELETE FROM TABLA
       WHERE  EXPRESIÓN; 
	   La claúsula where es optativa...... PERO LA USAMOS SIEMPRE..
	   CUANDO QUEREMOS VACIAR UNA TABLA, ES DECIR ELIMINAR TODAS SUS TUPLAS
	   USAMOS OTRA SENTENCIA Y NO DELETE FROM TABLA, SIN WHERE..*/
	 **/  
	   
  /**  PARA VACIAR UNA TABLA, 
        EN LUGAR SE USAR DELETE  SIN CLAÚSULA WHERE
        USAR SIEMPRE SENTENCIA TRUNCATE
**/

   /**  TRUNCATE PROYECTOS;
        **/
		
        /* ESTO SE EJECUTA DE FORMA DISTINTA  A UN DELETE TABLA SIN CLÁUSULA WHERE**/
		/* SE BORRA LA TABLA (DROP TABLA), SE EJECUTA  A CONTINUACIÓN UN CREATE TABLE**/
		
   
  /** ELIMINA EL REGISTRO DE TRABAJO EMPLEADO=3, PROYECTO=2**/
  /** PARA ELIMINAR UNA TUPLA EN UNA TABLA CUYA PK ES COMPUESTA, ATENCIÓN EN LA EXPRESIÓN  ...*/
  
  DELETE FROM EMPLEADOS_PROYECTOS
    WHERE EMPLEADO=3 AND PROYECTO=2; /** CERO O UNA TUPLA**/
   /* 1 row(s) affected**/
   
/** ELIMNINAR LOS REGISTROS DE TRABAJO 
     EN DONDE EL EMPLEADO  LLEVE MÁS DE 1900
     DIAS  DE TRABAJO
     **/
     DELETE FROM EMPLEADOS_PROYECTOS
       WHERE DATEDIFF(CURRENT_DATE(), FECHA_INICIO) > 1900;
   
 /*EL EMPLEADO DE CLAVE 3 SE JUBILA**/
 /* INVESTIGAMOS UN POCO..*/
 SELECT * FROM FAMILIARES WHERE EMPLEADO=3;  /* 1 TUPLA*/
 SELECT * FROM EMPLEADOS_PROYECTOS  WHERE EMPLEADO=3; /* 3 TUPLAS*/
 
 DELETE FROM empleados
    WHERE ID_EMPLEADO=3;
	
    /
			
    /** RESULTA  QUE SE OBTIENE ESTE MENSAJE DE ERROR:**/
	     NO SE PUEDE BORRAR DE LA BASE DE DATOS*/
 /* Error Code: 1451.
 Cannot delete or update a parent row: 
  a foreign key constraint fails 
  (`empresa`.`departamentos`, CONSTRAINT `departamentos_ibfk_1` 
  FOREIGN KEY (`DIRECTOR`) REFERENCES `empleados` (`ID_EMPLEADO`) 
  ON DELETE RESTRICT ON UPDATE CASCADE)
  **/
	
	
	/**UN EMPLEADO QUE ESTÉ REFERENCIADO COMO DIRECTOR NO PODRÁ SER ELIMINADO
	   DE LA BASE DE DATOS, PORQUE HEMOS DEJADO DEFINIDO PARA LA COLUMNA DIRECTOR
	   DE LA TABLA DEPARTAMENTOS ON DELETE RESTRICT**/
  
  /* CAMBIAMOS AL DIRECTOR**/
   UPDATE departamentos
       SET DIRECTOR =10
      WHERE NUMERO=3;
    
  /** 3 YA NO ES DIRECTOR.. SE PUEDE ELIMINAR**/
  DELETE FROM empleados
    WHERE ID_EMPLEADO=3;
  /*  1 row(s) affected**/
       NO SE PUEDE BORRAR DE LA BASE DE DATOS*/
 
  
  /**  SE ELIMINADO 1 TUPLA EN EMPLEADOS + 3 TUPLAS EN E_P, +1 TUPLA FAMILIARES*/


/** OTRO SUPUESTO: AHORA ELIMINAMOS AL EMPLEADO DE CLAVE 9
     ES UN SUPERVISOR, PORQUE ESTÁ REFERENCIADA SU CLVE EN LA COLUMNA SUPERVISOR**/

SELECT * FROM EMPLEADOS_PROYECTOS WHERE EMPLEADO=9;/*2 TUPLAS*/
SELECT * FROM FAMILIARES WHERE EMPLEADO=9; /*O TUPLAS*/
SELECT DIRECTOR  FROM DEPARTAMENTOS; /*9 NO ES DIRECTOR*/
SELECT * FROM EMPLEADOS WHERE SUPERVISOR=9; /* 2 TUPLAS*/

DELETE FROM EMPLEADOS 
   WHERE ID_EMPLEADO=9;

/*1 row(s) affected*/
/*** ---> 2 TUPLAS EN EP, MODIFICADO 2 TUPLAS EN EMPLEADOS**/ 

SELECT * FROM EMPLEADOS;


/*SUPONER AHORA  LA SIGUIENTE ORDEN  :
    ELIMINAMOS EL PROYECTO DE CLAVE 2, 
    SUPONER  QUE YA SE HA TERMINADO DICHO
    PROYECTO ***/
/** VAMOS A INVESTIGAR: */


SELECT * FROM PROYECTOS WHERE ID_PROYECTO=2;

SELECT COUNT(*)
    FROM EMPLEADOS_PROYECTOS
    WHERE PROYECTO=2; 
    /** 3 REGISTROS DE TRABAJO PARA   EL PROYECTO 2**/
    
  
/*DAMOS LA ORDEN  DE BORRADO: */

 DELETE FROM PROYECTOS
     WHERE ID_PROYECTO=2;
     /*  1 row(s) affected 
  ESTE MENSAJE  DE SALIDA " NO  ES MUY REAL", SE REFIERE A ESTA ORDEN DIRECTA EN ESTA TABLA,
  PERO SE ARRANCA EN NUESTRA BASE DE DATOS, PORQUE ASÍ LO HEMOS DEFINIDO UN BORRADO EN CASCADA*/
        

/***    esta orden arranca  internamente
         un  borrado en cascada en  la tabla empleados_proyectos,
         ELIMINAR PROYECTO DE CLAVE 2 DE LA BBDD,SE BORRAN 3 TUPLAS:
         1 TUPLA EN PROYECTOS
         Y 2 EN CASCADA EN TABLA EMPLEADOS_PROYECTOS ***/  
 
 /************************************************************************************************
/***SUPONER AHORA ESTAS ÓRDENES:
       1.   MODIFICAR  AL DIRECTOR DEL DEPARTAMENTO DE VENTAS
            EL NUEVO DIRECTOR SERÁ EL EMPLEADO DE CLAVE 10, HASTA 
            AHORA CONSTABA COMO DIRECTOR DE ESE DEPARTAMENTO  EL EMPLEADO DE CLAVE 2
        2. A CONTINUACIÓN, DAMOS DE BAJA O ELIMINAMOS DE LAS BASE DE DATOS
           AL EMPLEADO DE CLAVE 2
        3. ESTAS DOS OPERACIONES SE TIENE QUE REALIZAR EN ESTE ORDEN
           Y LAS UNIMOS EN UNA TRANSACCIÓN----> COSTRUÍMOS
            PARA TODOS LOS DEMÁS USUARIOS DE LA BASE DE DATOS
            UNA OPERACIÓN ATÓMICA CON ESTAS DOS ÓRDENES
            Y TODAS SUS CONSECUENCIAS INTERNAS
            (BORRADO EN CASCADA EN EMPLEADOS-PROYECTOS
            Y EN FAMILIARES)
            **/
START TRANSACTION;
        UPDATE DEPARTAMENTOS
		   SET DIRECTOR=10
		   WHERE DIRECTOR=2;
		                        /*ATENCIÓN PODEMOS ESCRIBIR LA ORDEN ASÍ
								  PORQUE DIRECTOR ES EN REALIDAD AK DE DEPARTAMENTO*/
        DELETE FROM EMPLEADOS
		  WHERE ID_EMPLEADO=2;
COMMIT;



    
 
 