/** EJEMPLO   DE USO SENTENCIA
                             CREATE TABLE AS SELECT
                             **/
/*** DESEAMOS CREAR UNA TABLA PARA REGISTRAR EN ELLA
     ESTA INFORMACIÓN:
          CLAVE DE CADA DEPARTAMENTO, NOMBRE DEL DEPARTAMENTO, CANTIDAD DE EMPLEADOS
          ASIGNADOS AL DEPARTAMENTO,  SALARIO MEDIO DE SUS EMPLEADOS
          CLAVE DE SU DIRECTOR , ANTIGUEDAD EN EL CARGO DE DIRECTOR (AÑO) , SALARIO DEL DIRECTOR 
          
          ******/
          
          
          
USE EMPRESA;


/**   PRIMERO DISEÑAMOS LA  CONSULTA**/
SELECT  
         D.NUMERO AS CLAVE_DEP,
         D.NOMBRE AS DEPARTAMENTO,
         COUNT(E.ID_EMPLEADO) AS NUMERO_EMPLEADOS,
         AVG(E.SALARIO)   AS SALARIO_MEDIO_DEP,
         D.DIRECTOR AS CLAVE_DIRECTOR, 
         YEAR(D.FECHA_INICIO) AS ANTIGUEDAD_DIRECTOR,
         (
           SELECT SALARIO
             FROM EMPLEADOS
             WHERE ID_EMPLEADO=D.DIRECTOR

          )  AS SALARIO_DIRECTOR
   FROM DEPARTAMENTOS AS D   LEFT JOIN EMPLEADOS AS E
                                                                  ON D.NUMERO=E.DEPARTAMENTO
   GROUP BY D.NUMERO;

CREATE DATABASE INFO_EMPRESA;

CREATE TABLE INFO_EMPRESA.DATOS_DEPARTAMENTOS
    AS  
    SELECT   
         D.NUMERO AS CLAVE_DEP,
         D.NOMBRE AS DEPARTAMENTO,
         COUNT(E.ID_EMPLEADO) AS NUMERO_EMPLEADOS,
         AVG(E.SALARIO)   AS SALARIO_MEDIO_DEP,
         D.DIRECTOR AS CLAVE_DIRECTOR,  
         YEAR(D.FECHA_INICIO) AS ANTIGUEDAD_DIRECTOR,
         (
           SELECT SALARIO
             FROM EMPLEADOS
             WHERE ID_EMPLEADO=D.DIRECTOR

          )  AS SALARIO_DIRECTOR
   FROM DEPARTAMENTOS AS D   LEFT JOIN EMPLEADOS AS E
                                                                 ON D.NUMERO=E.DEPARTAMENTO
   GROUP BY D.NUMERO; 


USE INFO_EMPRESA;
/** CONSULTAMOS NUESTRA NUEVA TABLA*/

SELECT * FROM DATOS_DEPARTAMENTOS;
/** PODEMOS REDISEÑARLA,  BAJAR EL MOTOR.... AGILIZAR CONSULTAS  CON .INDICES...*/
ALTER TABLE DATOS_DEPARTAMENTOS
     ENGINE MyISAM,
     ADD UNIQUE INDEX NOMBRE_DEP(DEPARTAMENTO);
     
  /*   4 row(s) affected Records: 4  Duplicates: 0  Warnings: 0   0.500 sec**/
