/******* 1º EJERCICIO *********************************************
  NECESITAMOS INCORPORAR A LA BASE DE DATOS
    LO SIGUIENTE:

     A CADA PROYECTO LE ASIGNAMOS
     UN EMPLEADO QUE ES SU TUTOR DE PROYECTO,
	 ESTO ES OBLIGATORIO PARA TODOS LOS PROYECTOS,DE MODO QUE,
	 UN PROYECTO NO PODRÁ ESTAR REGISTRADO
	 SIN SU CORRESPONDIENTE TUTOR.
     EL TUTOR PUEDE SER CUALQUIER EMPLEADO, 
	 SE REGISTRA TAMBIÉN LA FECHA DE ASIGNACIÓN DE LA TUTORÍA.
     UN EMPLEADO   PUEDE SER AL MISMO TIEMPO TUTOR DE VARIOS  PROYECTOS
     ******************************************************************/

/* REALIZAR OPERACIONES NECESARIAS PARA PODER REFLEJAR ESTA  NUEVA 
     INFORMACIÓN  EN LA BASE DE DATOS ***/

/* ASIGNAR  A CADA PROYECTO EXISTENTE EN ESTE MOMENTO 
     COMO TUTOR AL JEFE DE DEPARTAMENTO QUE CREA 
	 O LANZA EL PROYECTO
     FECHA DE TUTORÍA LA FECHA ACTUAL**/
/** PRIMERO SE TRATA DE INCORPORAR UNA NUEVA RELACIÓN EN LA BASE DE DATOS*/

ALTER TABLE PROYECTOS
   ADD COLUMN TUTOR INTEGER UNSIGNED  NULL, /*POR AHORA DEFINO NULL*/
   ADD COLUMN FECHA_TUTOR DATE NOT NULL,
   ADD FOREIGN KEY (TUTOR) REFERENCES EMPLEADOS(ID_EMPLEADO)
                            ON DELETE RESTRICT
                            ON UPDATE CASCADE,
   ADD  INDEX FK_TUTOR (TUTOR);                         

UPDATE PROYECTOS AS P
    SET P.TUTOR=(
                 SELECT  DIRECTOR
                    FROM DEPARTAMENTOS
                    WHERE NUMERO=P.DEPARTAMENTO
                    
              ),
        P.FECHA_TUTOR=CURRENT_DATE();    
/* ESTE UPDATE SE EJECUTA PARA TODAS Y CADA UNA DE LAS TUPLAS DE PROYECTOS*/        
    
ALTER TABLE PROYECTOS 
  MODIFY COLUMN TUTOR INTEGER UNSIGNED NOT NULL;





/******************************   2º EJERCICIO  *************************************************************/

/** CREAR UNA VISTA  LLAMADA VISTA_PROYECTOS
        QUE CONTENGA  PARA CADA PROYECTO:

             SU CLAVE, NOMBRE DEL PROYECTO,
             NOMBRE DE SU TUTOR DE PROYECTO,
             CANTIDAD DE EMPLEADOS TRABAJANDO EN ÉL
             TOTAL HORAS DE TRABAJO SEMANALES EN EL PROYECTO,
             FECHA DE PRIMERA ASIGNACIÓN  DE TRABAJO A ALGÚN EMPLEADO,
             CLAVE Y NOMBRE DEL DEPARTAMENTO QUE LO CREA
			 CANTIDAD DE EMPLEADOS DEL DEPARTAMENTO
   			  UE CREA EL PROYECTO QUE TRABAJAN ENEL PROYECTO
			  
*********************************************************************************/


/*****************  3º EJERCICIO*****************************************************************/

/*DESEAMOS OBTENER UNA TABLA(FICHERO DE DATOS) CON LA SIGUIENTE INFORMACIÓN
  PARA CADA FAMILIAR,  SU NIF, SU NOMBRE, FECHA DE NACIMIENTO, NIF Y NOMBRE DEL EMPLEADO
  QUE LO HA REGISTRADO Y PARENTESCO CON EL EMPLEADO,
  LOS REGISTROS DE ESTE FICHERO NOS INTERESAN ORDENADOS POR CLAVE DE
  DEPARTAMENTO AL QUE PERTENECE EL EMPLEADO Y POR NIF DE EMPLEADO******/

/*** A CONTINUACIÓN AGILIZAR LAS FUTURAS CONSULTAS A ESTE FICHERO,
     CREAR UN ÍNDICE  SOBRE COLUMNA NIF_FAMILIAR, OTRO SOBRE COLUMNA NIF_EMPLEADO
     Y UNÍNDICE EN NOMBRE FAMILIAR Y NOMBRE EMPLEADO PERO NO COMPLETOS, SÓLOAMENTE  CON 10 PRIMEROS
     CARACTERES DE CADA CADENA**/

/*******************
 4º INVESTIGAR LOS ÍNDICES EXISTENTES PARA LA TABLA EMPLEADOS DE  LA BASE DEDATOS EMPRESA

    CUÁL ES LA ORDEN QUE DEBES UTILIZAR ?
    ANALIZA  DETALLADAMENTE EL INFORME OBTENIDO DESDE LA EJECUCIÓN DE LA SENTENCIA

/*********************************************************************************************************/

/*****
            MySQL NOS PERMITE CREAR
            ÍNDICES COMPUESTOS DE HASTA 16 COLUMNAS, EL DATO ALMACENADO EN EL ÍNDICE
            ES LA CONCATENACIÓN DE LOS VALORES DE LAS COLUMNAS INDEXADAS,
            PARA OBTENER BENEFICIOS DE LA EXISTENCIA DEL ÍNDICE RECORDAD QUE EN  LAS EXPRESIONES 
            EN LAS QUERYS MANTENED EL ORDEN DE INDEXACIÓN  DEFINIDO AL CREAR ELÍNDICE DE IZQUIERDA A DERECHA, 
            SINO EL GESTOR NO EMPLEARÁ  EL ÍNDICE EN LA OPERACIÓN.
     *************************************************************/
     
     /***
            VAMOS A CREAR UNO EN FAMILIARES  PARA VER SU INFORME;
            CREAR UN ÍNDICE CON COLUMNAS  NOMBRE DE EMPLEADO, FECHA DE NACIMIENTO Y SEXO
            Y LUEGO EJECUTAR DE NUEVO LA SENTENCIA QUE NOS INFORMA DE LA EXISTENCIA DE LOS ÍNDICES
   ********************************************/         

